### PR TITLE
DRILL-6627: Adding REGEX_SUB_SCAN operator to protobuf file

### PR DESCRIPTION
**Pull request by vdiravka**

### CODE REVIEW

**Comment by vdiravka** [comment]
@arina-ielchiieva Please review

**Comment by arina-ielchiieva** [comment]
@vdiravka I believe you need to regenerate c++ code, @vvysotskyi could you please confirm.

**Comment by vvysotskyi** [comment]
Yes, I see the same constants in `UserBitShared.pb.h` file, so I believe c++ files also should be regenerated.

**Comment by cgivre** [comment]
HI @vdiravka 
Did you submit the updated .`proto` files or was I supposed to do it?  I'm fine either way.

**Comment by vdiravka** [comment]
@arina-ielchiieva @vvysotskyi Right, it seems this operator should be added to C++ proto file too.
I have added it and regenerated C++ protobuf files.

@cgivre This is not complicated, so I did it to make sure that it will be included to the Drill release.

**Comment by arina-ielchiieva** [comment]
+1, LGTM. @vdiravka thanks for the fix. Please merge when all Travis checks pass.

**Pull request merged**
