### PR TITLE
DRILL-5698 Escape version number period separator, this captures version numbers…

### PR DESCRIPTION
**Pull request by darrenbrien**
… with 4 5 or 6 in them, like 1.8.0_144

### CODE REVIEW

**Comment by arina-ielchiieva** [comment]
@darrenbrien thanks for the pull request but could please also create Jira for the fix [1], [2].

[1] https://issues.apache.org/jira/secure/RapidBoard.jspa?rapidView=185&projectKey=DRILL
[2] https://drill.apache.org/docs/apache-drill-contribution-guidelines/

**Comment by darrenbrien** [comment]
Jira https://issues.apache.org/jira/browse/DRILL-5698 created

**Comment by arina-ielchiieva** [comment]
+1, LGTM.

**Comment by josefloreschura** [comment]
I have the same issue and got here when I was about to create an issue.
It's can also be reproduced this way:

- Current behaviour

bash-3.2# echo "version 1.8.0_66" | grep "version" | egrep -e "1.4|1.5|1.6"
(no output)

bash-3.2# echo "version 1.8.0_144" | grep "version" | egrep -e "1.4|1.5|1.6"
version 1.8.0_144

- With the proposal fix

bash-3.2# echo "version 1.8.0_144" | grep "version" | egrep -e "1\.4|1\.5|1\.6"
(no output)

bash-3.2# echo "version 1.6" | grep "version" | egrep -e "1\.4|1\.5|1\.6"
version 1.6

Workaround (for now): install java version not containing 14, 15 16 in the version (revision)

**Comment by paul-rogers** [comment]
Please put the JIRA ticket number in the title so that the system will automagically send comments & close notices to the JIRA ticket. Example:

DRILL-5698: Escape version number period separator, this captures version numbers

**Comment by arina-ielchiieva** [comment]
@darrenbrien 
Can you please also rename the commit message as well, as Paul have mentioned there is a convention here to have Jira number at the beginning: `DRILL-5698: Escape version number period separator, this captures version numbers`

**Comment by darrenbrien** [comment]
see https://github.com/apache/drill/pull/899

**Comment by arina-ielchiieva** [comment]
There was not need to create new PR. You could just amend your commit message and use `git push -f`.

**Pull request closed without merging**
