### PR TITLE
[MINOR UPDATE]: Update the copyright year in NOTICE

### PR DESCRIPTION
**Pull request by CalvinKirs**

### CODE REVIEW

**Review by jnturton — CHANGES_REQUESTED** [review]
Thanks for this! Would you doing the same update in distribution/src/main/resources in this PR?

**Comment by CalvinKirs** [comment]
> Thanks for this! Would you doing the same update in distribution/src/main/resources in this PR?↳

Sure, this is my negligence, thank you for your reminder. 
However, it should be noted that our binary package still has license-related issues that need to be addressed.

**Review by jnturton — APPROVED** [review]

**Comment by cgivre** [comment]
@CalvinKirs Can you clarify what are the issues with the binary package?  This is the first I'm hearing of this.

**Comment by CalvinKirs** [comment]
> @CalvinKirs Can you clarify what are the issues with the binary package? This is the first I'm hearing of this. We'd definitely like to fix this.↳

Hi Charles,


I created a ticket [DRILL-8475](https://issues.apache.org/jira/browse/DRILL-8475) and James will work with me to improve the work here.

**Pull request merged**
