### PR TITLE
[DOC UPDATE] Index.html Chinese Translation

### PR DESCRIPTION
**Pull request by kingswanwho**
# [DOC UPDATE] Index.html Chinese Translation

## Description

Translate Index.html to Chinese version which referred to READ.me of gh-pages and the timely instruction from @dzamo (James Turton). 

## Documentation

This is a translation PR, reference to drill/gh-pages/zh/index.html

## Testing

This is a translation PR, no test here.

### CODE REVIEW

**Review by dzamo — CHANGES_REQUESTED** [review]
I see in that in the external links you remove the scheme "https:", probably by accidentally reverting to old code.  I recently added "https:" to these URLs because otherwise Polyglot thinks it must mangle them for multilingual, and of course it must not.  It is possible to use a special character to tell Polyglot to leave these URLs alone but instead I used an explict "https:" since that is a recommended practice these days.  This could be what has messed with your page layout so could you put "https:" back into every URL starting with "//" and see if the layout problems are fixed?

**Comment by kingswanwho** [comment]
> I see in that in the external links you remove the scheme "https:", probably by accidentally reverting to old code. I recently added "https:" to these URLs because otherwise Polyglot thinks it must mangle them for multilingual, and of course it must not. It is possible to use a special character to tell Polyglot to leave these URLs alone but instead I used an explict "https:" since that is a practice recommended in general these days. This could be what has messed with your page layout so could you put "https:" back into every URL starting with "//" and see if the layout problems are fixed?

Yes, I found the problem you mentioned, after I changed those thing to newest version you just submitted, the video switch framework bug I mentioned in slack back to normal. I will close this PR, and open a new one.

**Comment by luocooong** [comment]
@kingswanwho YES, Don't need to open new pull request. Because Git is a very powerful tool, the condition is that we have to master these skills, but most developers will mess it up at the beginning.
Well, I'm going to address some suggestions (for zh-CN) tomorrow.

**Comment by dzamo** [comment]
@kingswanwho just push a last commit with the fixes to kingswanwho:git-pages-zh-index.  This PR will automatically incorporate it.

**Review by dzamo — APPROVED** [review]

**Review by luocooong — CHANGES_REQUESTED** [review]
@kingswanwho Hello, I left some comments.

**Review by luocooong — APPROVED** [review]
@kingswanwho @dzamo LGTM. +1
Great work. Looking forward to your next contribution.

**Pull request merged**
