### PR TITLE
DRILL-6303: Provide a button to copy the Drillbit's JStack shown in /threads

### PR DESCRIPTION
**Pull request by kkhatua**
Provides a button in the web UI to copy the thread stack to the user's clipboard.

### CODE REVIEW

**Comment by kkhatua** [comment]
@arina-ielchiieva 

I've added 2 snapshots and tested in Chrome.

**Mouse Over**, showing tooltip
mouseover

**On clicking**, the copy of the text to the clipboard, followed by the alert.
mouseonclick

**Comment by arina-ielchiieva** [comment]
@kkhatua thanks for making the changes, it believe it's very useful but I suggest we do consider some design changes:
1. Information and auto-refresh display as badege and do not hard-code refresh limit.
2. Use glyphicon instead of regular button and move to right side. 
3. Simplify tooltip to `Copy to clipboard`.
4. Remove onlick logic.

**Comment by kkhatua** [comment]
@arina-ielchiieva I've made updates based on the review. 
image

I've also skipped adding re-adding the Glyphicons package because we already have that as part of DRILL-6279 (PR #1197 ).

**Comment by arina-ielchiieva** [comment]
+1

**Pull request closed without merging**
