### PR TITLE
DRILL-4816: Fix sqlline command line parsing (sqlline -f failed to re…

### PR DESCRIPTION
**Pull request by parthchandra**
…ad the query file)

### CODE REVIEW

**Comment by sudheeshkatkam** [comment]
+1

**Comment by paul-rogers** [comment]
+1

**Comment by paul-rogers** [comment]
Because you are fixing an issue with the scripts changes, please add the following as well to drill-config.sh:

    # Source distrib-env.sh for any distribution-specific settings.
    # distrib-env.sh is optional; it is created by some distribution installers
    # that need distribution-specific settings.
    # Because installers write site-specific values into the file, the file
    # should be moved into the site directory, if the user employs one.
    
    distribEnv="$DRILL_CONF_DIR/distrib-env.sh"
    if [ -r "$distribEnv" ]; then
      . "$distribEnv"
    else
      distribEnv="$DRILL_HOME/conf/distrib-env.sh"
      if [ -r "$distribEnv" ]; then
        . "$distribEnv"
      fi
    fi

The above replaces the existing block of code for distrib-env.sh.

**Comment by sudheeshkatkam** [comment]
Please open another ticket for that issue.

**Comment by parthchandra** [comment]
Paul, yes, please create a new Jira for this and create a new pull request for the change you want.

**Pull request closed without merging**
