### PR TITLE
DRILL-8405: Upgrade to snakeyaml 2.0 due to CVE

### PR DESCRIPTION
**Pull request by pjfanning**
## Description

upgrade to snakeyaml 2.0 due to CVE - also upgrades liquibase jar because we need a version of that jar that supports newer APIs of snakeyaml

## Testing
CI build

### CODE REVIEW

**Review by cgivre — APPROVED** [review]
LGTM +1. (Pending CI)
Thanks @pjfanning

**Comment by cgivre** [comment]
Ugh.. it looks like the new library broke something.   Disregard approval. :-(

**Comment by pjfanning** [comment]
It looks like Liquibase uses a snakeyaml 1.0 API call that is not supported in snaleyaml 2.0.

```
2023-02-26T15:12:21.4680779Z Caused by: java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.SafeConstructor: method <init>()V not found
2023-02-26T15:12:21.4681347Z 	at liquibase.parser.core.yaml.YamlChangeLogParser.parse(YamlChangeLogParser.java:23)
2023-02-26T15:12:21.4681830Z 	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:369)
```

**Comment by cgivre** [comment]
@pjfanning Is there any workaround for this?

**Comment by pjfanning** [comment]
Need to wait for liquibase to upgrade their lib. I don't know if snakeyaml is used elsewhere in Drill. If it is, it may be possible to upgrade snakeyaml in some places and keep the old version where liquibase is used.

**Comment by cgivre** [comment]
@pjfanning I'm going to convert this to draft status until we can update liquibase.

**Comment by pjfanning** [comment]
@cgivre one of the CI subtasks is taking a bit longer to complete but it looks like using the new liquibase jar has fixed this general issue

**Comment by cgivre** [comment]
@pjfanning I'll keep an eye on it, but it looks good.  I'll restart if it times out.

**Pull request merged**
