### PR TITLE
Issue DRILL-3736 - fixed syntax of partition by.

### PR DESCRIPTION
**Pull request by ebegoli**
It was incorrectly listed as PARTITION_BY. Changed to PARTITION BY.

### CODE REVIEW

**Comment by kristinehahn** [comment]
Thanks, I also fixed this in my repo 13 days ago https://github.com/kristinehahn/drill/tree/gh-pages/_docs/sql-reference/sql-commands, but haven't been able to get it committed.

**Comment by ebegoli** [comment]
I have pull request in place so just merge it :-)

**Comment by kristinehahn** [comment]
Sorry I can't merge or close this pull request, ^ ("Only those with write access . . ."), but I fixed the problem. Please close this pull request. Thanks for flagging the mistake.

**Comment by ebegoli** [comment]
Kristen fixed it. I am closing pull request.

**Pull request closed without merging**
