### PR TITLE
DRILL-6215: Changed Statement to PreparedStatement in JdbcRecordReader

### PR DESCRIPTION
**Pull request by khurram-faraaz**
@bitblender @kkhatua  Can you please review ?
JDBC unit tests ran clean for me.

### CODE REVIEW

**Comment by kkhatua** [comment]
@kfaraaz Are there unit tests specific to the JDBC Storage Plugin? They're not the same as the JDBC unit tests, which test the Drill JDBC driver.

While the change seems straightforward, I'm not sure if all JDBC drivers support PreparedStatement. For e.g., within Drill, the PreparedStatement is executed as a standard Statement object, which is why this _works_ functionally.

What happens if a JDBC driver backing the JDBC storage plugin does not support PreparedStatement (i.e. it is a No-Op)?

**Comment by kfaraaz** [comment]
I don't know about the other file, I didn't add it. Let me check.

Thanks,
Khurram

**Comment by arina-ielchiieva** [comment]
@kfaraaz did you have a chance to address issue with second file?

**Comment by vvysotskyi** [comment]
Fixed in https://github.com/apache/drill/commit/4f55e71dc971d42054a031acd000ddf8337e90d9

**Pull request closed without merging**
