### PR TITLE
DRILL-6438: Remove excess logging form tests.

### PR DESCRIPTION
**Pull request by ilooner**
## Changes

 - Removed excess print statements from tests
 - Switched all System.out and System.err statements in the tests to loggers

### CODE REVIEW

**Comment by ilooner** [comment]
@arina-ielchiieva

**Comment by priteshm** [comment]
@vvysotskyi could you please review this?

**Comment by vvysotskyi** [comment]
@ilooner, could you please remove other places in tests where results are printed using `System.out.println()`. For example, in TestHiveUDFs it also may be removed; for every HBase test its result is printed for now.

Also, may be changed value of the option `drill.test.query.printing.silent` to reduce output.

**Comment by ilooner** [comment]
Sure I'll try to remove them from the other tests as well. Some of the extra logging I might not be able to remove. For example a lot of the MongoDB logging comes from separate MongoDB server processes the test launches with the flapadoodle library.

**Comment by arina-ielchiieva** [comment]
@ilooner what about banning `System.out` and `e.printStackTrace()`? Will this be addressed in different PR? If yes, could you please point out to the Jira?

**Comment by vvysotskyi** [comment]
Thanks for so many changes!
The output for some tests (`TestSimpleProjection`, `TestConvertFunctions` etc.) is printed using methods from `VectorUtil`. It would be fine to change the output for these methods.

**Comment by ilooner** [comment]
@arina-ielchiieva I made this Jira to track banning those functions. https://issues.apache.org/jira/browse/DRILL-6464

@vvysotskyi I converted the print statements to log statements in VectorUtil

**Comment by arina-ielchiieva** [comment]
@ilooner thanks for creating the Jira and making the changes, looks good to me.

**Pull request closed without merging**
