### PR TITLE
BACKPORT-TO-STABLE: Backported fixes for Drill 1.21.2

### PR DESCRIPTION
**Pull request by jnturton**
# [BACKPORT-TO-STABLE]: fixes for Drill 1.21.2

## Description

Fixes and minor enhancements since Drill 1.21.1 backported from the master branch.

### CODE REVIEW

**Comment by cgivre** [comment]
@jnturton 
Did we add https://github.com/apache/drill/pull/2795 to this?

**Comment by jnturton** [comment]
> @jnturton Did we add #2795 to this?

@cgivre yes, it's here.

**Review by luocooong — APPROVED** [review]
LGTM +1

**Comment by cgivre** [comment]
@jnturton 
I'd like to include DRILL-8470, and possibly DRILL-8415 and DRILL-8465 in this.  What do you think?  I'm on the fence about DRILL-8465 as that does seem like more of a new feature.

**Comment by jnturton** [comment]
> @jnturton I'd like to include DRILL-8470, and possibly DRILL-8415 and DRILL-8465 in this. What do you think? I'm on the fence about DRILL-8465 as that does seem like more of a new feature.

8415 and 8470 are here. 8465 is still in analysis and design. We still need the new 8475 (NOTICE file incomplete) that I marked as a blocker and which is being worked on by @CalvinKirs and me.

**Pull request merged**
