### PR TITLE
Replace git-wip-us reference with gitbox

### PR DESCRIPTION
**Pull request by vvysotskyi**

### CODE REVIEW

**Comment by arina-ielchiieva** [comment]
@bbevens could you please review and merge?

**Comment by vvysotskyi** [comment]
@bbevens, did you have a chance to take a look at this?
In this PR was only replaced obsolete links to the remote repository, since it caused problems for new drill users: https://stackoverflow.com/questions/53516086/apache-drill-assertionerror-relational-expression/53525547#comment94039836_53525547

**Comment by bbevens** [comment]
Hi Volodymyr,
I resolved the conflict, but I'm not able to rebase and merge. Can you accept the conflict resolution and then hopefully I'll be able to Rebase and merge the changes.
Thanks,
Bridget

**Comment by vvysotskyi** [comment]
Hi @bbevens, thanks for the review, I did the rebase, so now it can be merged.

**Comment by bbevens** [comment]
Hi @vvysotskyi, thank you! I've built the site and pushed the changes; your updates are posted.

**Pull request merged**
