### PR TITLE
DRILL-4995: Allow lazy init when dynamic UDF support is disabled

### PR DESCRIPTION
**Pull request by arina-ielchiieva**

### CODE REVIEW

**Comment by sudheeshkatkam** [comment]
+1

**Comment by sudheeshkatkam** [comment]
I take back my +1; this fails unit tests.

**Comment by arina-ielchiieva** [comment]
Fixed ExpressionTreeMaterializerTest.testMaterializingLateboundTreeValidated and rebased on current master.

**Comment by parthchandra** [comment]
+1 Unit tests are passing now.

**Pull request closed without merging**
