### PR TITLE
DRILL-5849: Add freemarker lib to dependencyManagement to ensure prop…

### PR DESCRIPTION
**Pull request by arina-ielchiieva**
…er version is used when resolving dependency version conflicts

Details in [DRILL-5849](https://issues.apache.org/jira/browse/DRILL-5849).

### CODE REVIEW

**Comment by vrozov** [comment]
The proposed changes simplify the dependency management, but do not change the dependency resolution, AFAIK.

**Comment by arina-ielchiieva** [comment]
@vrozov as far as I understand to manage dependency resolution, you can either exclude conflicting dependencies or use dependency management mechanism [1, 2]. I have used dependency management mechanism since it's more convenient and you don't have to track new conflicting dependencies. If you know it's not sufficient, please let us know what is the best solution.

[1] https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html
[2] http://techidiocy.com/maven-dependency-version-conflict-problem-and-resolution/

**Comment by vrozov** [comment]
@arina-ielchiieva I refer to java-exec and fmpp modules dependencies resolution. Both AFAIK should not be affected by the change, so I suppose it is another module that has a transitive dependency on freemarker through java-exec and another 3rd party library that has the issue described in the JIRA. Please confirm and provide details on the module and the 3rd party library.

**Comment by arina-ielchiieva** [comment]
@vrozov 
1. Change the the main pom.xml where I have added freemarker lib to the `dependencyManagement` section is the core change of this pull request. With this change dependency resolution is always done in favor of the freemarker version we expect.
2. Changes in other two pom files are just clean up. Since as we now have freemarker lib in `dependencyManagement` there is no need to indicate version there.
3. Regarding which modules do have transitive dependency on freemarker, right now there are two modules  - java-exec (jersey-mvc-freemarker lib) and fmpp (fmpp lib).

**Pull request closed without merging**
