### PR TITLE
DRILL-4020: The not-equal operator returns incorrect results when used on the HBase row key

### PR DESCRIPTION
**Pull request by nagix**
* Added a condition that checks if the filter to the scan specification doesn't have NOT_EQUAL operator
* Added testFilterPushDownRowKeyNotEqual() to TestHBaseFilterPushDown

### CODE REVIEW

**Comment by jacques-n** [comment]
Shoot, I mistyped my close message. Should have been 283 instead of 238. @nagix, can you reopen this pull request?

**Comment by nagix** [comment]
@jacques-n, I don't believe I can re-open this because I didn't close it. Can you do it or do l need to open a new request?

**Comment by jacques-n** [comment]
Maybe just submit new request. I can't reopen either.

**Comment by nagix** [comment]
Submitted a new request #309

**Pull request closed without merging**
