### PR TITLE
DRILL-5917: Ban org.json:json library in Drill

### PR DESCRIPTION
**Pull request by vrozov**
@arina-ielchiieva Please review

### CODE REVIEW

**Comment by arina-ielchiieva** [comment]
@vrozov when I have deployed Drill with your changes on test cluster, Drill start up failed with the following error:
```
2017-11-13 01:30:12,3367 ERROR JniCommon fs/client/fileclient/cc/jni_MapRClient.cc:616 Thread: 26996 Mismatch found for java and native libraries java build version 5.2.2.44680GA, native build version 5.2.2.44680.GA java patch vserion $Id: mapr-version: 5.2.2.44680GA 44680:b0ba7dcefd80b9aaf39f05f3, native patch version $Id: mapr-version: 5.2.2.44680.GA 44680:b0ba7dcefd80b9aaf39f05f
2017-11-13 01:30:12,3368 ERROR JniCommon fs/client/fileclient/cc/jni_MapRClient.cc:626 Thread: 26996 Client initialization failed.
Exception in thread "main" org.apache.drill.exec.exception.DrillbitStartupException: Failure during initial startup of Drillbit.
	at org.apache.drill.exec.server.Drillbit.start(Drillbit.java:353)
	at org.apache.drill.exec.server.Drillbit.start(Drillbit.java:323)
	at org.apache.drill.exec.server.Drillbit.main(Drillbit.java:319)
Caused by: org.apache.drill.common.exceptions.DrillRuntimeException: Error during udf area creation [/user/root/drill/udf/registry] on file system [maprfs:///]
	at org.apache.drill.common.exceptions.DrillRuntimeException.format(DrillRuntimeException.java:49)
	at org.apache.drill.exec.expr.fn.registry.RemoteFunctionRegistry.createArea(RemoteFunctionRegistry.java:277)
	at org.apache.drill.exec.expr.fn.registry.RemoteFunctionRegistry.prepareAreas(RemoteFunctionRegistry.java:234)
	at org.apache.drill.exec.expr.fn.registry.RemoteFunctionRegistry.init(RemoteFunctionRegistry.java:105)
	at org.apache.drill.exec.server.Drillbit.run(Drillbit.java:167)
	at org.apache.drill.exec.server.Drillbit.start(Drillbit.java:349)
	... 2 more
Caused by: java.io.IOException: Could not create FileClient
	at com.mapr.fs.MapRFileSystem.lookupClient(MapRFileSystem.java:626)
	at com.mapr.fs.MapRFileSystem.lookupClient(MapRFileSystem.java:679)
	at com.mapr.fs.MapRFileSystem.makeDir(MapRFileSystem.java:1239)
	at com.mapr.fs.MapRFileSystem.mkdirs(MapRFileSystem.java:1276)
	at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:1917)
	at org.apache.drill.exec.expr.fn.registry.RemoteFunctionRegistry.createArea(RemoteFunctionRegistry.java:254)
	... 6 more
```
Without your changes start up was successful.

**Comment by vrozov** [comment]
@arina-ielchiieva Please attach the full log to JIRA.

**Comment by arina-ielchiieva** [comment]
@vrozov I have posted all content of drillbit.out. drillbit.log just had information that could not create remote function registry directory.

**Comment by vrozov** [comment]
@arina-ielchiieva Please test with the latest commit. I changed mapr version back to 5.2.1, note that 2.7.0-mapr-1707 is compiled with 5.2.2

**Comment by vrozov** [comment]
@arina-ielchiieva Please test

**Comment by arina-ielchiieva** [comment]
Test cluster is down for the weekend. You can test it locally, just run {{mvn clean install -Pmapr}}.

**Comment by vrozov** [comment]
I already tested mapr and default profile locally. Once test pass on your cluster, let me know and I'll squash commits.

**Comment by arina-ielchiieva** [comment]
I see some functional test failures but I don't think they are related, it might be that your branch is not based on the latest master, so +1, LGTM.
@vrozov thanks for making the changes!

**Comment by vrozov** [comment]
rebased to upstream/master and squashed commits.

**Pull request closed without merging**
