### PR TITLE
DRILL-8071: use excel cell.getLocalDateTimeCellValue

### PR DESCRIPTION
**Pull request by pjfanning**
# [DRILL-8071](https://issues.apache.org/jira/browse/DRILL-8071): use excel cell.getLocalDateTimeCellValue

## Description

Use built-in POI/excel-streaming-reader method to get date time - this is safer than writing custom code to convert excel numbers to date times. In particular, this method takes into account if the workbook stores date times with 1900 or 1904 as the base date.

## Documentation
No changes

## Testing
Unit tests

### CODE REVIEW

**Comment by pjfanning** [comment]
@cgivre this PR covers one of the issues in DRILL-8701 - is it ok that I use the try-catch block and just log errors that happen when cell.getLocalDateTimeCellValue fails?

**Comment by cgivre** [comment]
> 

@pjfanning Thanks for this PR.  You've hit on an issue which is subject to a lot of different opinions.  The issue at stake is how do you read data without a schema and what do you do when the data is inconsistent?

I'm approaching this from the data scientist/user perspective and I am just one data point, but here goes.  I really like the way Pandas handles the whole situation.  Specifically, Pandas does attempt to infer data types, but also gives the user a lot of control over the behavior when things go wrong.   I think Pandas lets the user decide if it throws an exception, ignores it, or coerces a value.  

I don't know if that's more work than you want to do, but I do feel that logging isn't quite enough because that assumes that a user has logging enabled and can view the logs.  If there was a config option on error handling, it could be changed at query time with the `table()` function.

**Comment by pjfanning** [comment]
@cgivre I removed the new logging

I agree that it would be nice to have some configuration to decide what to with errors. I think this PR is probably better to stick to just the date time conversion issue.

If Drill does not currently have support for supporting conversion errors - could I suggest that one possible approach is to have excel like cell comments? - so that Drill could put a default value in the Drill cell equivalent but attach a comment with the error. It would still be useful to support fail fast as an option too (ie fail the upload if any cells can't be loaded as the type the schema says they are).

**Review by cgivre — APPROVED** [review]
LGTM +1

**Pull request merged**
