### PR TITLE
DRILL-8357: Add new config options to the Splunk storage plugin

### PR DESCRIPTION
**Pull request by jnturton**
# [DRILL-8357](https://issues.apache.org/jira/browse/DRILL-8357): Add new config options to the Splunk storage plugin

## Description

The Splunk SDK and testcontainer are upgraded to 1.9.1 and 9 respectively. New config options supported by the Splunk SDK are added. None are required and none are present in the Splunk config template.

| Name                 | Description                                                     |
| -------------------- | --------------------------------------------------------------- |
| scheme             | The scheme with which to access the Splunk host.          |
| app                  | The application context of the service.                         |
| owner                | The owner context of the service.                               |
| token                | A Splunk authentication token to use for the session.           |
| cookie               | A valid login cookie.                                           |
| validateCertificates | Whether the Splunk client will validates the server's SSL cert. |

In an accompanying commit the storage.plugin_auto_disable SYSTEM option default is changed from true to false so that users must explictly choose to have the auto disabler active.

## Documentation
Added new options to [the Splunk plugin doc page](https://drill.apache.org/docs/splunk-storage-plugin/).

## Testing
Set the config options and check that they are passed through to the Splunk SDK in SplunkConnection.

### CODE REVIEW

**Comment by cgivre** [comment]
@jnturton The PR looks good. I had a few questions:
1.   Could you please document what types of input would be expected in these fields and what they do?   I'm not really clear myself what the `owner` field actually does.  If you're not sure, then let's leave it, but if you had some additional info, that would be helpful.
2.  I had question about the `token` and `cookie`?  Are these fields something that we'd expect to be set in a config, or are they something that should be somehow populated dynamically?   This seemed strange to me.

**Review by cgivre — APPROVED** [review]
LGTM +1 

I had some documentation questions, but the code looks good.

**Comment by jnturton** [comment]
> I had question about the token and cookie? Are these fields something that we'd expect to be set in a config, or are they something that should be somehow populated dynamically? This seemed strange to me.

I thought they might be set in the config _and_ dynamic i.e. the user's application obtains a token or cookie from Splunk and then updates the Drill config with it using the Drill REST API. Or in the config and static if the user [has gone to Splunk Web for a token](https://docs.splunk.com/Documentation/Splunk/latest/Security/CreateAuthTokens#Use_Splunk_Web_to_create_authentication_tokens) that lives for a long enough time that doing this would make sense.

**Comment by jnturton** [comment]
Busy updating README.md (which I'd forgotten about) and the website doc page with more information about Apps and Owners.

**Comment by jnturton** [comment]
@kingswanwho please note the backport label I just added to this merged PR and also to #2706.

**Pull request merged**
