### PR TITLE
DRILL-7950: Drill classpath includes both avatica-core:jar:1.15.0 and avatica:jar:1.17.0

### PR DESCRIPTION
**Pull request by vvysotskyi**
# [DRILL-7950](https://issues.apache.org/jira/browse/DRILL-7950): Drill classpath includes both avatica-core:jar:1.15.0 and avatica:jar:1.17.0

## Description
```
mvn dependency:tree -Dincludes=org.apache.calcite.avatica:avatica* -pl contrib/storage-cassandra,contrib/storage-elasticsearch

[INFO] ----------< org.apache.drill.contrib:drill-storage-cassandra >----------
[INFO] Building Drill : Contrib : Storage : Cassandra 1.19.0              [1/2]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ drill-storage-cassandra ---
[INFO] org.apache.drill.contrib:drill-storage-cassandra:jar:1.19.0
[INFO] +- org.apache.drill.exec:drill-java-exec:jar:1.19.0:compile
[INFO] |  \- org.apache.calcite.avatica:avatica:jar:1.17.0:compile
[INFO] \- com.github.vvysotskyi.drill-calcite:calcite-cassandra:jar:1.21.0-drill-r2:compile
[INFO]    \- org.apache.calcite.avatica:avatica-core:jar:1.15.0:compile
[INFO]       \- org.apache.calcite.avatica:avatica-metrics:jar:1.15.0:compile
[INFO]
[INFO] --------< org.apache.drill.contrib:drill-storage-elasticsearch >--------
[INFO] Building Drill : Contrib : Storage : ElasticSearch 1.19.0          [2/2]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ drill-storage-elasticsearch ---
[INFO] org.apache.drill.contrib:drill-storage-elasticsearch:jar:1.19.0
[INFO] +- org.apache.drill.exec:drill-java-exec:jar:1.19.0:compile
[INFO] |  \- org.apache.calcite.avatica:avatica:jar:1.17.0:compile
[INFO] \- com.github.vvysotskyi.drill-calcite:calcite-elasticsearch:jar:1.21.0-drill-r2:compile
[INFO]    \- org.apache.calcite.avatica:avatica-core:jar:1.15.0:compile
[INFO]       \- org.apache.calcite.avatica:avatica-metrics:jar:1.15.0:compile
```

## Documentation
NA

## Testing
NA

### CODE REVIEW

**Review by luocooong — APPROVED** [review]
LGTM. +1

**Comment by cgivre** [comment]
@vvysotskyi Could you please rebase on current master?  It seems one of the tests is failing in the http plugin.
Thx!

**Comment by vvysotskyi** [comment]
@cgivre, this is a random failure, please see run on the same commit (870a489) for my local branch: https://github.com/vvysotskyi/drill/runs/2758472300

**Comment by cgivre** [comment]
> @cgivre, this is a random failure, please see run on the same commit ([870a489](https://github.com/apache/drill/commit/870a48916b850dc275cf2b74a1a26cca67beb849)) for my local branch: https://github.com/vvysotskyi/drill/runs/2758472300

Are we good to merge?

**Comment by vvysotskyi** [comment]
I think yes.

**Pull request merged**
