### PR TITLE
DRILL-7205: Drill fails to start when authentication is disabled

### PR DESCRIPTION
**Pull request by agozhiy**

### CODE REVIEW

**Comment by vvysotskyi** [comment]
@agozhiy, change looks good, but is it possible to add a unit test for this change?
I found similar tests in `TestCustomUserAuthenticator`.

**Comment by agozhiy** [comment]
@vvysotskyi, done.

**Comment by vvysotskyi** [comment]
@agozhiy, please squash the commits.

**Comment by agozhiy** [comment]
@vvysotskyi, done.

**Pull request closed without merging**
