### PR TITLE
DRILL-4546: Only generate one zip archive when using apache-release profile

### PR DESCRIPTION
**Pull request by laurentgo**
Drill root pom doesn't override completely Apache parent pom configuration
regarding assemblies, which caused a zip archive of the project to be generated
twice, and deployed to a remote server twice too.

The fix updated the Apache parent pom version, and uses the plugin properties
to override the configuration. Also remove Drill source assembly descriptor as
the Apache parent project provides the same one.

### CODE REVIEW

**Comment by jacques-n** [comment]
Can you confirm that the release artifacts do not change between applying this and not applying it?

**Comment by laurentgo** [comment]
The only changes to the resulting src bundles are the changes to pom.xml file, the missing assembly file which has been removed by the patch and changes to the git.properties file (because of the patch commit).

The distributions tar.gz have the same git.properties difference + some jar differences (which are likely caused by differences in the META-INF/METADATA.MF). There's no file missing or added

**Comment by ilooner** [comment]
@laurentgo Any interest in rebasing this?

**Comment by vdiravka** [comment]
It is resolved in PR #1561

**Pull request closed without merging**
