### PR TITLE
DRILL-8301: Try to ensure char to byte (and vice versa) conversions use utf-8 encoding

### PR DESCRIPTION
**Pull request by pjfanning**
Plenty of Drill code uses UTF-8 already. The problem is lots more Drill code uses the JVM default. There is a lot of inconsistency.

### CODE REVIEW

**Comment by jnturton** [comment]
I wonder whether hard coding UTF-8 is the way to go here? If we leave the conversion operations in the code using the JVM default then users can still set that to UTF-8 using the JVM system property `file.encoding="UTF-8"`. But they could also choose to set that sytem property to something else...

**Comment by pjfanning** [comment]
@jnturton There is lots of existing Drill code using UTF-8 explicitly. The current code is very inconsistent. And if we would want to strip all the existing UTF8 code, we would need to start testing Drill with many different -Dfile.encoding settings to find out if the code works for a large subset of the possible charsets.

**Comment by jnturton** [comment]
> @jnturton There is lots of existing Drill code using UTF-8 explicitly. The current code is very inconsistent.

I did see that 😒. Whatever we do, I think this should be promoted from a minor update to a Jira. We'll want to take a deliberate decision about character encoding that we hold to in the future.

**Comment by jnturton** [comment]
I guess there are two different classes of character data.

1. Internal use character data where we can use whatever encoding we like and perhaps would choose based on performance (would that suggest UTF-16?).
2. Interchange character data that we share with the outside world, e.g. a JSON file that Drill wants to query. It feels like it would be nice if we can accept different encodings here. I wonder what Jackson and friends do w.r.t. character encodings.

**Comment by pjfanning** [comment]
With jackson - JSON spec (https://www.ietf.org/rfc/rfc4627.txt) mandates unicode with utf-8 as default. XML mandates utf-8 as default. Quite rare in my experience to see other Unicode charsets used. Utf-8 encoding should use fewer bytes for Latin alphabet based text and numeric data.

Java strings can now use utf-16 internally. I'm not sure if there is a performance impact using utf-16 instead of utf-8 (https://www.dariawan.com/tutorials/java/java-9-compact-string-and-string-new-methods/).

My main concern is correctness and testability as opposed to performance. Choosing one encoding for externally facing data and another internally would introduce a lot of extra complexity and possibly confusion as to which to choose in certain scenarios - and possibly lower performance as you would often need to convert between the 2 encodings.

**Review by jnturton — APPROVED** [review]
Thanks for this improvement to Drill and hanging on to allow discussion.

**Review by cgivre — APPROVED** [review]
LGTM +1

**Pull request merged**
