### PR TITLE
DRILL-2304: Case sensitivity - system and session options are case sensitive

### PR DESCRIPTION
**Pull request by sudheeshkatkam**
@jaltekruse please review.

### CODE REVIEW

**Comment by sudheeshkatkam** [comment]
Addressed review comments mentioned on 313c8e3 f33654c

**Comment by jaltekruse** [comment]
@sudheeshkatkam I reviewed this change while I was looking at 3497 in #98. Other than the few small comments over there this looks good.

**Comment by sudheeshkatkam** [comment]
Passes all unit and regression tests.

**Comment by jaltekruse** [comment]
+1

**Pull request closed without merging**
