### PR TITLE
DRILL-8089: Separate the setup time for some operators

### PR DESCRIPTION
**Pull request by Leon-WTF**
# [DRILL-8089](https://issues.apache.org/jira/browse/DRILL-8089): Separate the setup time for some operators

## Description
Calculate setup time separately for some operators

## Documentation
No need

## Testing
By existed ut

### CODE REVIEW

**Review by paul-rogers — APPROVED** [review]
LGTM. +1

**Comment by cgivre** [comment]
@Leon-WTF I see this marked as draft, but @paul-rogers approved it.  Is this ready to merge or are you planning on adding more to this PR?  

If you are ready to merge, please remove the `draft` and we'll merge!  Thanks for the contribution and Happy New Year!!

**Comment by Leon-WTF** [comment]
> @Leon-WTF I see this marked as draft, but @paul-rogers approved it. Is this ready to merge or are you planning on adding more to this PR?
> 
> If you are ready to merge, please remove the `draft` and we'll merge! Thanks for the contribution and Happy New Year!!

@cgivre Seams that I don't have the permission to remove the Draft... Can you help to do that?

**Comment by Leon-WTF** [comment]
> @Leon-WTF I see this marked as draft, but @paul-rogers approved it. Is this ready to merge or are you planning on adding more to this PR?
> 
> If you are ready to merge, please remove the `draft` and we'll merge! Thanks for the contribution and Happy New Year!!
@cgivre Done!

**Pull request merged**
