### PR TITLE
DRILL-8154: Upgrade to poi 5.2.1

### PR DESCRIPTION
**Pull request by pjfanning**
## Description

Latest poi release

## Documentation
(Please describe user-visible changes similar to what should appear in the Drill documentation.)

## Testing
(Please describe how this PR has been tested.)

### CODE REVIEW

**Review by luocooong — APPROVED** [review]
LGTM. +1

**Comment by pjfanning** [comment]
@luocooong I don't have rights to merge this PR. If you have merge rights, would it be possible for you to merge this?

**Comment by luocooong** [comment]
@pjfanning Sure, thanks for the updating the version.

**Comment by jnturton** [comment]
> @luocooong I don't have rights to merge this PR. If you have merge rights, would it be possible for you to merge this?

@pjfanning I think you do have the ability to merge now that you're a committer?

**Comment by pjfanning** [comment]
@jnturton I do not have a 'merge' button in github for this PR or any other Drill PR.

**Comment by jnturton** [comment]
> @jnturton I do not have a 'merge' button in github for this PR or any other Drill PR.

There's some stuff you need to do to link your Apache account to your Github account. I think it's at id.apache or whimsy.apache. My guess is that this is what's missing.

**Comment by jnturton** [comment]
@pjfanning I had the wrong sites there, the account linking is at https://gitbox.apache.org

**Comment by pjfanning** [comment]
@jnturton thanks - I'll try that out

**Pull request merged**
