### PR TITLE
DRILL-8199: Convert Excel EVF1 to EVF2

### PR DESCRIPTION
**Pull request by jnturton**
# [DRILL-8199](https://issues.apache.org/jira/browse/DRILL-8199): Convert Excel EVF1 to EVF2

## Description

The Excel format plugin is upgraded to use the EVF 2 framework.

## Documentation
N/A

## Testing
Existing unit tests, manual testing.

### CODE REVIEW

**Comment by jnturton** [comment]
@cgivre or @luocooong, something that the upgrade to EVF 2 broke in this plugin is the unit test TestExcelFormat::testStarWithProvidedSchema. Now the metadata columns which should be excluded from star query results are present and making this test fail. For this reason I've left this PR in draft status. Is there something obvious that I've done wrong?

**Comment by jnturton** [comment]
It looks like the unit test scheduling we've got at the moment sometimes produces errors in TestUserTranslationInHttpPlugin (not related to this PR)

**Review by cgivre — APPROVED** [review]
LGTM +1 (Pending CI)

**Comment by luocooong** [comment]
@jnturton Sorry for the delay. It looks like the bug left over from the upstream code processing the unprojection, and I'll check it.

**Pull request merged**
