### PR TITLE
[MINOR UPDATE]: Disable lgtm build

### PR DESCRIPTION
**Pull request by pjfanning**
Removes a file that is no longer needed.

### CODE REVIEW

**Comment by cgivre** [comment]
In thinking about this further, I think we need to open a ticket with INFRA to remove LGTM.

**Comment by pjfanning** [comment]
@cgivre I raised https://issues.apache.org/jira/browse/INFRA-23627

**Comment by cgivre** [comment]
@pjfanning  The INFRA ticket was closed and LGTM is now no longer active on the repo.

**Comment by pjfanning** [comment]
@cgivre thanks for sorting out the INFRA ticket. This PR is now really just for removing a file that is no longer needed.

**Review by cgivre — APPROVED** [review]
LGTM +1

**Comment by cgivre** [comment]
I'm fine with merging as is, but there are a bunch of LGTM comments in the code to ignore false positives.  Should we remove those here as well, or separate PR?

**Comment by pjfanning** [comment]
@cgivre I just removed the lgtm comments. A common pattern used in the code that were highlighted as index out bounds risks - I think LGTM was right, so I've made the same change in those cases. The change was to use the hasNext() method to see if it possible to increment the counter.

**Comment by pjfanning** [comment]
@cgivre Github code scanning picked up on some of the pre-existing issues - otherwise, the build seems ok

**Comment by jnturton** [comment]
@pjfanning @cgivre it seems that the way to suppress Github's code analysis warnings is by manually dismissing them so it looks to me like we're good to go here.

**Pull request merged**
