### PR TITLE
DRILL-8454: Disable unsupported MapR profile and plugin

### PR DESCRIPTION
**Pull request by jnturton**
# [DRILL-8454](https://issues.apache.org/jira/browse/DRILL-8454): Disable unsupported MapR profile and plugin

## Description

The MapR build profile and format plugin, which fell out of support in the open source Drill codebase years ago, are disabled. Drill users needing support for these components should contact HPE.

## Documentation
See the HPE Ezmeral docs.

## Testing
Build and unit tests of remaining modules pass.

### CODE REVIEW

**Comment by jnturton** [comment]
This one's ready for review.

**Comment by jnturton** [comment]
A note to the reviewers. Git's default diff algorithm makes it very hard to see that the changes this PR makes to pom.xml are simply whole sections moving into comment blocks. GitHub does not allow selection diff algorithm at this time so, to ease review, I have therefore [uploaded the diff of pom.xml generated using `git diff --diff-algorithm=patience` separately](https://gist.github.com/jnturton/f7a623046da2861bad93419529ff78b3). It is of course also possible to run this locally after pulling down my branch.

**Comment by rymarm** [comment]
@jnturton Hi! I'll take a look at this pull request this week later or even next week. I've just got back from a vacation and got on a "burning boat" of work)

But I have a question now, Why did you decide to comment the mapr specific changes, but not completely remove them?

And in addition, I suppose that we also need to remove mentions of maprdb support from the [documentation](https://drill.apache.org/docs/mapr-db-format/) or leave a link to HPE documentation.

**Comment by jnturton** [comment]
@rymarm welcome back! I wasn't sure whether to delete or comment out the mapr modules. I decided to try moving them to new, commented out sections of "Objects of type foo that are no longer supported" that seemed to keep an informative history in the source files without a lot of extra cruft. But that history is always available in Git so I'm also happy to delete instead...

**Review by cgivre — APPROVED** [review]
LGTM +1
In general I don't like leaving commented out code blocks, but in the event that someone wants to use a current version of Drill with MapR, I do think it is fine to leave them for a while.

**Comment by cgivre** [comment]
@jnturton Can we merge this?

**Comment by jnturton** [comment]
@cgivre let me convert the comment blocks to deletions as suggested by you and @rymarm and then let's merge it.

**Pull request merged**
