### PR TITLE
can drill support minio s3 storage

### PR DESCRIPTION
**Pull request by rongfengliang**
can drill support minio s3 storage  i can't find any config property for s3 endpoint  in documents

### CODE REVIEW

**Comment by kkhatua** [comment]
@rongfengliang I'm not sure what commit this is? Are you asking a question about support for S3, because we already have a user-mailing list?
The S3 storage plugin is already supported : https://drill.apache.org/docs/s3-storage-plugin/
So you should be able to use Drill to query minio S3 as well.

**Comment by vrozov** [comment]
@rongfengliang If you have a question regarding Drill ask it on `user@drill.apache.org`. If you have something to contribute, please follow contributions guidelines to open a PR.

**Comment by vrozov** [comment]
Can one of PMCs request INFRA to close the PR?

**Comment by arina-ielchiieva** [comment]
Created request - https://issues.apache.org/jira/browse/INFRA-16390

**Comment by rongfengliang** [comment]
@kkhatua @vrozov  @arina-ielchiieva   so sorry for this ,  because i  don't find the  new issue button . i will create  request in jira

**Pull request closed without merging**
