### PR TITLE
DRILL-4295: Removes obsolete protobuf-generated files

### PR DESCRIPTION
**Pull request by laurentgo**
These files are obsolete protobuf-generated files, whose definition has been removed.

### CODE REVIEW

**Comment by jacques-n** [comment]
Can you look at a way to update the -Pproto-compile code so it first deletes all the files so we don't have this kind of problem in the future?

**Comment by laurentgo** [comment]
I can check on how to delete first, but maybe you can share why these files are persisted in the first place under git, versus being generated everytime: is it because you have to install protobuf compiler first?

**Comment by jacques-n** [comment]
Fair question. For the first year the codebase only generated these files at build time (no check-in). In this situation newcomers had to install the right version of protoc. This turned into the single biggest issue on the dev list to new contributors. As such, we finally relented and committed the compiled code. (In general, the problem is that if brew/macports installs the wrong version, people get strange maven compilation problems that are non-obvious).

**Comment by laurentgo** [comment]
If changing protobuf version to 2.6.1 is an option, maven central now has protoc version for each architecture, that the protobuf maven plugin can take advantage of: http://sergei-ivanov.github.io/maven-protoc-plugin/faq.html#faq_1

**Comment by jacques-n** [comment]
I'm not sure it is a simple option. I believe we have to worry about version conflicts between Drill, HDFS, HBase and MapRFS. (We used to shade for this purpose but we stopped once we were all on the same version).

**Comment by laurentgo** [comment]
I was expecting this, so I added the clean before generate source code

**Comment by jaltekruse** [comment]
+1 on the clean change and removal of unnecessary files.

If we want to try to clean up the build process to not check in the generated files, I assume that will be done in a follow up PR.
For now it doesn't sound like it's worth the hassle though.

**Pull request closed without merging**
