### PR TITLE
DRILL-4573 Fixed issue with regexp_replace function

### PR DESCRIPTION
**Pull request by jcmcote**
@jinfengni here's the new pull request.

### CODE REVIEW

**Comment by jcmcote** [comment]
There was an error in the continuous integration
Failure to transfer org.kududb:kudu-client:pom:0.6.0 
Does not seem related to the changes made in the pull request...

**Comment by jcmcote** [comment]
@jinfengni  can you apply this pull request. There's build issue but looks to be related to pom.xml files which I have not changed..

**Comment by jinfengni** [comment]
@jcmcote , I'll take a look at the patch shortly. You are right that the build issue should not be caused by your code change.

**Comment by sudheeshkatkam** [comment]
@jcmote can you please close this PR?

The changes were merged as part of #512

**Pull request closed without merging**
