### PR TITLE
DRILL-4111: turn tests off in travis as they don't work there

### PR DESCRIPTION
**Pull request by julienledem**
turn tests off in travis as they don't work there

### CODE REVIEW

**Comment by jacques-n** [comment]
Can we keep this but change to -DskipTests to verify compilation?

**Comment by julienledem** [comment]
updated to turn off tests instead

**Comment by julienledem** [comment]
travis-ci is gree: mvn package -DskipTests=true

**Comment by sudheeshkatkam** [comment]
:+1:

**Comment by julienledem** [comment]
Thanks @sudheeshkatkam. Did you mean to commit this?

**Comment by sudheeshkatkam** [comment]
+1

**Comment by julienledem** [comment]
Thank you!

**Pull request closed without merging**
