### PR TITLE
DRILL-7532: Convert Syslog to EVF

### PR DESCRIPTION
**Pull request by cgivre**
# [DRILL-7532](https://issues.apache.org/jira/browse/DRILL-7532): Convert Syslog to EVF

## Description

Converts the Syslog format plugin to use EVF. 

## Documentation
There are no changes visible to the user.

## Testing
Ran unit tests associated with the syslog plugin.  Added unit tests for compressed files, SerDe and limit pushdown.

### CODE REVIEW

**Review by luocooong — COMMENTED** [review]
The reader must read rows to determine the schema when `isComplete=false` ?

**Comment by cgivre** [comment]
> The reader must read rows to determine the schema when `isComplete=false` ?

The syslog format has a mix of known and unknown fields, so we have to set `isComplete` to `false`.

**Review by luocooong — COMMENTED** [review]
I recommend remove the useless spaces at `boolean isProjected (ScalarWriter writer)`.

**Review by luocooong — APPROVED** [review]

**Review by vdiravka — COMMENTED** [review]
minor things, which I did not manage to submit in time, but which can be considered for future commits

**Pull request merged**
