### PR TITLE
DRILL-3589: Update JDBC driver to shade and minimize dependencies.

### PR DESCRIPTION
**Pull request by jacques-n**

### CODE REVIEW

**Comment by dsbos** [comment]
It seems that you have shaded references to every Java package other than org.apache.drill.** (not just for every package from every depended-on artifact, but for _every_ package--including JDK packages).

Note how the following command says it can't find "oadd/java/sql/Driver":

$ java -cp ./exec/jdbc-all/target/drill-jdbc-all-1.2.0-SNAPSHOT.jar org.apache.drill.jdbc.Driver
Exception in thread "main" java.lang.NoClassDefFoundError: oadd/java/sql/Driver
...

It seems that in trying to load org.apache.drill.jdbc.Driver it tried to load its base class, normally java.sql.Driver from the JDK, but the reference to that base class was shaded to oadd.org.java.sql.Driver, so of course it couldn't be found.

(The expected behavior of that command is an error that org.apache.drill.jdbc.Driver doesn't have a main method.)


What setup did you use to test the shading?

**Comment by dsbos** [comment]
Something seems to be broken.

After rebasing your branch on my branch with my DRILL-3347 (Hadoop Test) and DRILL-3566 (Prep.Stmt.) fixes, I tried installing the resulting JDBC-all Jar file on Spotfire, but Spotfire's getting IndexOutOfBoundsExceptions somewhere within ResultSet.next().

I'll see if I can identify which shading might be causing that or what's going on in next().

**Comment by dsbos** [comment]
Another problem is that Logback logging might be broken (although maybe I just configured it wrong):

When I added (on Spotfire's class path) a Jar file containing a logback.xml file in order to turn on logging, instead of getting log messages, I got these messages:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

My guess is that whatever module we intended to provide org.slf4j.impl.StaticLoggerBinder isn't included in the JDBC-all Jar file now.

**Comment by dsbos** [comment]
Regarding SLF4J and what should or shouldn't be included in the JDBC-all Jar file:

Do we intend that someone using the JDBC-all Jar file can turn on Drill JDBC-layer logging by adding to the class path only a logback.xml file (that is, without adding additional Jar files/classes)?  If so, then it seems like the JDBC-all Jar file is probably missing the logback-classic Jar file (which contains a org.slf4j.impl.StaticLoggerBinder).

Or is it the case that we're leaving out back-end SLF4J libraries/classes on purpose (perhaps to avoid interfering with the user's choice of which back end to use)?

**Comment by jacques-n** [comment]
Can you start by reviewing my branch? Let's get it right before we try rebasing.

With regards to slf4j and logging: I have corrected the behavior versus the old packaging. We support any slf4j logging tool but we don't package any. This means that a user can leverage their existing logging framework. If we include a logging framework, then a user can't use their own for centralized logging. We'll need to doc this but it is on purpose.

**Comment by dsbos** [comment]
> Can you start by reviewing my branch? Let's get it right before we try rebasing.

I'm confused by that part of your comment.  I have been reviewing your branch, and I think I've reviewed the latest (with-test/without-ProGuard) version of it (hence my earlier review comments, and your replies to them).

Have I missed a message or am I looking at the wrong thing?  (I have been and am looking at this [Pull Request #116](https://github.com/apache/drill/pull/116).)

Also, your mention of rebasing sounds like a reference to a preceding request to rebase, but I don't see or recall any mention of rebasing your patch.


Looking again, I see that I just skimmed over the class loader that's just for the test.  Is it that you wanted more review of that class?

Oh--it is that I hadn't indicated that I was done reviewing it because I didn't give a +1 yet?  I hadn't done that before because I was waiting for confirmation on my SLF4J question.  You have answered that now (below), so the patch seems "plus-oneable" unless the resolution of whatever the confusion is here reveals a problem with the patch.


> With regards to slf4j and logging: ... We support any slf4j logging tool but we don't package any. ... 
> If we include a logging framework, then a user can't use their own for centralized logging...

Roger.  Yeah, I thought it might be that.

**Comment by jacques-n** [comment]
I'm confused too.  I got this comment in my email:

"Something seems to be broken.

    After rebasing your branch on my branch with my DRILL-3347 (Hadoop Test) and DRILL-3566 (Prep.Stmt.) fixes, I tried installing the resulting JDBC-all Jar file on Spotfire, but Spotfire's getting IndexOutOfBoundsExceptions somewhere within ResultSet.next()."

But I don't see it here. I was saying, lets make sure that this patch works as is before rebasing on 3347 and 3566.

**Comment by dsbos** [comment]
Okay, now I think I see what happened.

First of all, you can now ignore that "Something ... broken ..." comment; it's obsolete.  (Your patch no longer seems broken.)

(At first I thought things didn't work, and added that comment.  Then I noticed that I had a local version/build mismatch, and amended the comment to say "hold on; I'm checking again," and tested again.  Then everything worked, so I just deleted the comment from the GitHub review.  Next time I'll amend rather than delete.)

And now I recognize the "rebasing" reference:  I didn't mean rebasing like rebasing on the latest version of master.  I was just mentioning that rebasing was what I happened to use (as opposed to cherry-picking, merging, or other patching), in case my choice there caused the apparent breakage, to apply patches for DRILL-3347 and DRILL-3566 so I could try you patch with Spotfire (with would have hit the DRILL-3347 and DRILL-3566 bugs).

So ...

Your patch seems good; Spotfire ran fine with it.

**Comment by dsbos** [comment]
Would it be better if the JDBC-all Jar file didn't contain a logback.xml file?

If the JDBC-all Jar doesn't already have that file, then to configure logback differently with their own logback.xml file, users only have to get their own file on the classpath _somewhere_.

However, if the JDBC-all Jar does already have that file, it seems that users will have to get their logback.xml file on the class path _before_ the JDBC-all Jar file (right?).  Although sometimes that's trivial, when the class path is set by, say, listing all .jar files in a lib/ directory (e.g., as in Tomcat for Spotfire), controlling the order might not be possible or easy.

(A solution to keep the contents of the logback.xml file (as a convenient starting point for the user to copy out and modify) in the JDBC-all JAR file but not really have an active/interfering actual logback.xml file would be to use a modified name (e.g, logback-example.xml).)

**Comment by jacques-n** [comment]
Agree on the logback. That shouldn't in there. An oversight on my part.  We should be purely logging aganostic.

**Comment by dsbos** [comment]
+1 (non-binding) once logback.xml is removed

**Comment by jaltekruse** [comment]
+1

**Comment by dsbos** [comment]
@jacques-n, can you close this pull request (given that that 4e3b7dc0333a01e72d0ea9256331ea1e1dd51181 is in)?

**Pull request closed without merging**
