### PR TITLE
DRILL-7448: Fix warnings when running Drill memory tests

### PR DESCRIPTION
**Pull request by KazydubB**
Jira - [DRILL-7448](https://issues.apache.org/jira/browse/DRILL-7448)

### CODE REVIEW

**Comment by vvysotskyi** [comment]
@KazydubB, thanks for fixing it. Could you please add also Janino dependency into other places where `drill-common:tests` is used to avoid possible issues for unit tests in other modules? Also, please add a comment above added dependencies with the info why it should be present.

**Comment by KazydubB** [comment]
@paul-rogers, @vvysotskyi I've updated the PR with @vvysotskyi 's suggestion. Thank you!

**Comment by arina-ielchiieva** [comment]
@KazydubB thanks for making the changes. Discussed this issue with @vvysotskyi, it looks like adding janino dependency to all modules (and then control that it is added in new ones), might be slightly an overhead. I understand that we need to do this to support conditional processing which is mainly used to enable Lilith. On the other hand, we can remove condition, and leave Lilith code commented. Those who need Lilith would have to uncomment this code, instead of setting the variable. I suspect Lilith usage is not that popular in project and there won't be many complaint about it.

**Comment by KazydubB** [comment]
@arina-ielchiieva, yes, this is definetely better. Thank you!
@arina-ielchiieva, @vvysotskyi, @paul-rogers I've yet another change (according to Arina's last comment), please take a look again.

**Comment by arina-ielchiieva** [comment]
+1, LGTM.

**Pull request closed without merging**
