### PR TITLE
DRILL-4455: Depend on Apache Arrow

### PR DESCRIPTION
**Pull request by StevenMPhillips**
Remove the vector and memory modules
Replace most instances of TypeProtos.MajorType, TypeProtos.MinorType etc
  with corresponding org.apache.arrow.types.Types class.
The code for serializing and deserializing vectors is still in the Drill code-base
  and still uses the old TypeProtos classes. The class MajorTypeHelper is used
  to convert between the two sets of classes.
The old load and getMetadata classes in ValueVector are now found in a corresponding
  ValueVectorHelper class

### CODE REVIEW

**Comment by jaltekruse** [comment]
@StevenMPhillips Can you separate out the package renames into their own commit? It would be useful to see any meaningful code changes isolated. The diff is so big that it can't all be viewed/commented on in the github interface.

**Comment by StevenMPhillips** [comment]
I just rebased the patch and broke it up into 5 different patches.

**Comment by parthchandra** [comment]
I have two problems with this patch (apart from it being just too big to review) 
1) Building against 0.1-SNAPSHOT of a project that is in rapid development is a courageous decision (I would rather not board a train while it is moving at full speed). The current patch also does not build as there is no artifact for Arrow 0.1-SNAPSHOT.
2) I see that the entire memory module of Drill is gone. I don't think that drill memory management and accounting should be outsourced to Arrow. I can see needing to use ArrowBuf for value vectors but removing the entire memory module is not OK. I can see other uses of Direct/Heap memory (caching metadata for example) that should be managed under a Drill resource manager. This ties back to #1. Arrow needs to get its design figured out to allow Drill and other projects to manage their resources while providing a 'reference' implementation. 
-1 until we resolve this.

**Comment by jacques-n** [comment]
Sounds like we need to do some more work to mature and stabilize the Arrow code. Let's pick this up again once we've made more progress on that front.

**Comment by ilooner** [comment]
@vrozov Since you are picking up Drillbuf design work, please advise on the plan for this PR.

**Comment by arina-ielchiieva** [comment]
Closing PR as outdated, new PR will be openned, see [DRILL-4455](https://issues.apache.org/jira/browse/DRILL-4455) for details.

**Pull request closed without merging**
