### PR TITLE
DRILL-4364: Image Metadata Format Plugin

### PR DESCRIPTION
**Pull request by nagix**
Initial commit of the Image Metadata Format Plugin

### CODE REVIEW

**Comment by zfong** [comment]
@vkorukanti, @jaltekruse, @adityakishore - since each of you have written format plugins in the past, can one of you help code review this change?

**Comment by cgivre** [comment]
@nagix Are you still working on this?  What is the status?

**Comment by nagix** [comment]
@cgivre Yes, I'm still working on this. Since the dependent library (metadata-extractor) has been updated, I need to add some changes according to it. I will push another commit shortly.

**Comment by nagix** [comment]
@cgivre I have made the code up to date. Can you review this?

**Comment by cgivre** [comment]
@nagix I'd be happy to review it, but I'm not a Drill committer.

**Comment by cgivre** [comment]
@nagix I just became a committer, and I'd really love to see this incorporated into the latest version of Drill.  Are you willing to keep working on this to finish it?  If not, I may have some time to complete it. 
Thx!

**Comment by nagix** [comment]
Congratulations, @cgivre! I will check the latest version of the dependent library, and rebase this branch.

**Comment by kkhatua** [comment]
@nagix Did you get a chance to rebase this commit?

**Comment by cgivre** [comment]
@nagix Can you please fix the conflict with `exec/java-exec/pom.xml`?    Please also squash the commit.

**Comment by nagix** [comment]
@cgivre I have fixed the conflict and squashed the commit.

**Comment by cgivre** [comment]
+1 LGTM.  Built successfully and ran queries in embedded mode.  Thank you for your contribution to Drill!

**Pull request closed without merging**
