### PR TITLE
Elasticsearch storage plugin

### PR DESCRIPTION
**Pull request by hamdanuk**
Would you please add Elasticsearch storage plugin.

### CODE REVIEW

**Comment by xwinie** [comment]
drill query mongodb plugin show Chinese garbled!
image  
image  所有中文显示都是乱码！

**Comment by sudheeshkatkam** [comment]
@hamdanuk and @xwinie please ask questions on the user list. Details [are here](http://drill.apache.org/mailinglists/).

@hamdanuk can you please close this pull request? Our project uses pull requests for code review.

**Comment by xwinie** [comment]
I send mail to dev<dev@drill.apache.org>. but no body reply. I had an urge to solve this problem. Please help to see if the problem!

**Comment by xycloud** [comment]
any update?

**Comment by xycloud** [comment]
any progress about this commit?

**Comment by kkhatua** [comment]
@hamdanuk this commit has too many commits, which makes the PR nearly impossible to review. Would you like to rebase your work on the latest Drill 1.12.0 and try again?

**Comment by arina-ielchiieva** [comment]
@amansinha100 / @parthchandra should we close this PR as invalid?

**Comment by cgivre** [comment]
Is there any code in this PR that actually relates to Elastic Search?  Personally, I'd love to see Drill have an Elasticsearch storage plugin.

**Comment by arina-ielchiieva** [comment]
Maybe it was but definitely it's not now.

**Pull request closed without merging**
