### PR TITLE
DRILL-6625: Intermittent failures in Kafka unit tests

### PR DESCRIPTION
**Pull request by aravi5**
### Fix producer errors
- Increase the value of `ProducerConfig.REQUEST_TIMEOUT_MS_CONFIG` to accomadate slower systems.
- Increase the value of producer `ProducerConfig.RETRIES_CONFIG` to 3 (from 0).
- Prevent producer to send duplicate messages due to retries by setting `ProducerConfig.ENABLE_IDEMPOTENCE_CONFIG` to `true`.

### Fix consumer errors
- Increase `ExecConstants.KAFKA_POLL_TIMEOUT` (from 200 ms).

### Stabilize KafkaFilterPushdownTest
- Catch the issue with setup early by checking if expected number of records exist before running tests in `KafkaFilterPushdownTest` class.

Please refer to [DRILL-6625](https://issues.apache.org/jira/browse/DRILL-6625) for more details about the fix.

### CODE REVIEW

**Comment by vdiravka** [comment]
@aravi5 With this changes DRILL-6733 is still an issue?

**Comment by Ben-Zvi** [comment]
@aravi5 - Please also change the status of the jira (https://issues.apache.org/jira/browse/DRILL-6625) to 
 **REVIEWABLE**

**Comment by aravi5** [comment]
As a part of PR https://github.com/apache/drill/pull/1464, we discussed that some changes would go in as a part of this PR. Just checked in those changes.

@Ben-Zvi  @vdiravka @ilooner - Please review the new changes.

**Comment by aravi5** [comment]
The design of `TestKafkaSuit` is very similar to design of `MongoTestSuit` and hence needed changes similar to the ones made in [storage-mongo/pom.xml](f5dfa56#diff-e110e2cbfd77d27e85d5121529c612bfR83).

Current behavior is that surefire runs test classes twice - once as a part of `TestKafkaSuit` and the other by directly running classes. To prevent the latter from happening, changes were made (by @ilooner ) in `pom.xml` for `storage-mongo` plugin. Similar changes are made in `storage-kafka`.

**Pull request closed without merging**
