### PR TITLE
DRILL-6259: Support parquet filter push down for complex types

### PR DESCRIPTION
**Pull request by arina-ielchiieva**
Details in [DRILL-6259](https://issues.apache.org/jira/browse/DRILL-6259).

### CODE REVIEW

**Comment by priteshm** [comment]
@parthchandra can you please review this change?

**Comment by parthchandra** [comment]
+1. LGTM

**Comment by amansinha100** [comment]
@arina-ielchiieva could you rebase this on latest master ? thanks.

**Comment by arina-ielchiieva** [comment]
Done.

**Pull request closed without merging**
