### PR TITLE
DRILL-4574: Avro Plugin: Flatten does not work correctly on record items

### PR DESCRIPTION
**Pull request by baunz**
See https://issues.apache.org/jira/browse/DRILL-4574

### CODE REVIEW

**Comment by jacques-n** [comment]
Nice first patch. Thanks for the contribution.

+1

Can you collapse this into a single commit and make sure the commit message matches the Drill style: 

DRILL-XXXX: A short description

Longer description....

**Comment by baunz** [comment]
Done!

**Comment by amansinha100** [comment]
I ran the unit tests with your pull request on top of the current master branch   One of your new tests failed.  Can you take a look ? 

Results :

Failed tests: 
  AvroFormatTest.testFlattenEmptyComplexArray:394 Different number of records returned expected:<10000> but was:<0>

Tests run: 1743, Failures: 1, Errors: 0, Skipped: 128

**Comment by jaltekruse** [comment]
@amansinha100 It looks like the expected output of the test is just wrong, flattening an empty array should produce 0 rows.

**Comment by baunz** [comment]
@amansinha100 Thanks for helping out! As for the empty arrays: This is kind of embarassing: Creating a failing test asserting wrong behaviour that fails and issueing a pull request.

I will update the pull request..

**Comment by baunz** [comment]
I corrected the test and rebased the current master. Thanks for the input!

**Comment by Lceeba** [comment]
Hello Team,
              Any lead or help if there is a patch on Drill 1.5 or 1.6 to
support CQL or Cassandra ??

Appreciate your feedback or lead..

Thanks,
Lokesh

**Comment by amansinha100** [comment]
@Lceeba can you ask your question on the drill user list instead of in the pull request (you might want to check the mailing list first for prior similar question).

**Comment by amansinha100** [comment]
@baunz  unit test looks good now.  +1

**Pull request closed without merging**
