### PR TITLE
DRILL-4123: refer to fully qualified variable names; make file separa…

### PR DESCRIPTION
**Pull request by hnfgns**
…tor platform dependent

### CODE REVIEW

**Comment by jaltekruse** [comment]
This should not be using the File.Separator, as it is working with Hadoop and will always get Unix paths, even when running on Windows. Please see the JIRA linked below.

https://issues.apache.org/jira/browse/DRILL-3107

**Comment by hnfgns** [comment]
Thanks for the pointer. For some reason, I had this impression that File.separator relies on underlying FS and not the native one. I will revert.

**Comment by jaltekruse** [comment]
One other point here, the issue with fully qualified names actually shouldn't be a problem in the usual usage of this function. The function was only designed to be evaluated at planning time with the interpreter, not with the full code compilation model in the project operator. While not ideal, the expected error that should be hit if this function is used in a select list is here in the FragmentContext when we go to populate the injected PartitionExplorer. https://github.com/apache/drill/blob/master/exec/java-exec/src/main/java/org/apache/drill/exec/ops/FragmentContext.java#L458

Has there been work to make partition pruning run the full code generation based expression evaluation? I would consider anyone hitting code generation issues with this function to be misusing it, I agree with fixing this poor error, but anyone executing this function outside of partition pruning is going to be running a very expensive operation for each record in their dataset and I can't think of a use case for it.

**Comment by hnfgns** [comment]
Yeah, I am aware of the thrown warning. However, note that in the lieu of this fix user faces a compilation exception before the warning is shown when explorers are used in projection. Also, I definitely see a good use case for projecting the outcome of explorers like inspecting partition pruning. This patch has no means to address these though.

**Comment by jaltekruse** [comment]
Apologies, didn't think about the order in which compilation and resolving the injectables would be executed. I thought I had verified that this error would make it back to users if the function was used in a select list, but obviously there wasn't a test for it.

As far as looking at the output of explorers, the easiest way to do this would be to use a function like maxdir in the where clause and then just include dirN in the select clause as well. This will cause the function to be evaluated just during pruning.

select dir0 from dfs.workspace`path/to/dir/*` where dir0 = MAXDIR('dfs.workspace', '/path/to/dir');

**Comment by hnfgns** [comment]
Cool. This reminds me, I should add a test now :) Thanks for the projection example.

**Comment by vvysotskyi** [comment]
Problem with code gen was fixed in #391.

**Pull request closed without merging**
