### PR TITLE
DRILL-8421: Parquet microsecond columns

### PR DESCRIPTION
**Pull request by handmadecode**
# [DRILL-8421](https://issues.apache.org/jira/browse/DRILL-8421): Truncate parquet microsecond columns

## Description

The metadata min and max values of parquet microsecond columns are truncated to milliseconds, which is the time unit expected by the initial file pruning during filtering. Also, `TIME_MICROS` columns are read as 64-bit values before they are truncated to 32-bit milliseconds values. Previously they were read as 32-bit values, causing values > `Integer.MAX_VALUE` to be incorrect.

The second fix also addresses [DRILL-8423](https://issues.apache.org/jira/browse/DRILL-8423).

## Documentation
Bugfix only, no documentation changes

## Testing
Unit tests added in new test class `org.apache.drill.exec.store.parquet.TestMicrosecondColumns`.

### CODE REVIEW

**Comment by cgivre** [comment]
@handmadecode 
Thanks for the contribution and welcome to Drill!  Would you mind rebasing once [DRILL-8424] (https://github.com/apache/drill/pull/2794) is merged?   There are some CI issues which will be fixed by that PR.
Thanks!

**Comment by handmadecode** [comment]
@cgivre thanks, happy to contribute. I will rebase when 8424 is merged.

**Comment by jnturton** [comment]
> Thanks for the contribution and welcome to Drill! Would you mind rebasing once https://github.com/apache/drill/pull/2794 is merged?

Heh, I just came here to type exactly this. I reviewed the code changes and they look great so really we just need the CI run after rebasing.

**Comment by cgivre** [comment]
@handmadecode https://github.com/apache/drill/pull/2794 has been merged.

**Review by jnturton — APPROVED** [review]
Thanks for this contribution!

**Comment by handmadecode** [comment]
@jnturton Happy to help!

**Pull request merged**
