### PR TITLE
DRILL-4270: Create a separate WindowFramer that supports the FRAME cl…

### PR DESCRIPTION
**Pull request by adeneche**
…ause

separate DefaultFrameTemplate into 2 implementations: one that supports custom frames (aggregations, first_value, last_value) and one that doesn't

### CODE REVIEW

**Comment by adeneche** [comment]
The purpose of this PR is to separate the functions that support the FRAME clause in CustomFrameTemplate from the ones that don't in DefaultFrameTemplate. Work still needs to be done to make the refactoring complete (like making sure code is not duplicated between the templates), but I decided to leave it after I make the necessary changes to support the FRAME clause.

@amansinha100 can you please review ?

**Comment by amansinha100** [comment]
Overall refactoring looks ok.  One thing that needs some clarity: Is the definition of default frame 'between unbounded preceding and current row' ?  If the user explicitly specifies this frame in the query, will it be treated as default or custom frame  (as opposed to not specifying anything frame) ?

**Comment by adeneche** [comment]
According to the SQL specification you can have a FRAME clause with FIRST_VALUE, LAST_VALUE or aggregate functions. Custom frame template will be used for those functions regardless of the presence/absence of the FRAME clause.

**Comment by adeneche** [comment]
maybe I should rename the templates to FrameTemplate and NoFrameTemplate instead of CustomFrameTemplate and DefaultFrameTemplate

**Comment by amansinha100** [comment]
Renaming sounds fine to avoid misinterpretation.  +1.

**Pull request closed without merging**
