### PR TITLE
DRILL-8417: Allow Excel Reader to Ignore Formula Errors

### PR DESCRIPTION
**Pull request by cgivre**
# [DRILL-8417](https://issues.apache.org/jira/browse/DRILL-8417): Allow Excel Reader to Ignore Formula Errors

## Description
If Drill encounters an Excel formula which is invalid somehow, such as a `DIV/0`, Drill is unable to proceed and throws a number format exception. 
This PR adds a config parameter called `ignoreErrors` which allows Drill to skip such records and returns `null` for that cell.  Drill will also output a log warning.  When set to `false`, original behavior is retained.

## Documentation
Updated README

* `ignoreErrors`:  Defaults to `false`.  When set to `true` Drill will return `null` for any
  formulas or any values that are unparseable.

## Testing
Added two unit tests.

### CODE REVIEW

**Review by jnturton — CHANGES_REQUESTED** [review]
My only request is that the config option defaults to false to remain consistent with everything else where the default is that invalid data breaks the query.

**Comment by cgivre** [comment]
> 

@jnturton
I updated the PR to default to `false` and updated the README as well.

**Comment by jnturton** [comment]
Reviewer's note: all format-excel tests do pass, the CI test failures here are a result of as yet unfixed breakage brought in by Calcite 1.35-SNAPSHOT.

**Comment by cgivre** [comment]
Once https://github.com/apache/drill/pull/2794 is merged, I'll rebase and merge this, pending @jnturton's approval.

**Review by jnturton — APPROVED** [review]
+1 pending CI.

**Pull request merged**
