### PR TITLE
DRILL-3623: Optimize limit 0 queries

### PR DESCRIPTION
**Pull request by StevenMPhillips**
This pulls some patches that Sudheesh had previously worked on but not committed. In addition, fixes some problems when the type is not one of the json ExtendTypes.

There are still problems with float, decimal, and interval_day/year.

### CODE REVIEW

**Comment by sudheeshkatkam** [comment]
@StevenMPhillips This is still WIP, right?

@hsuanyi and I plan to post an update soon.

**Comment by StevenMPhillips** [comment]
@hhsuanyi I did not open any calcite jira. The new calcite version was there from Sudheesh's commit which I pulled in.

@sudheeshkatkam Does your update handle limit 0 for all types?

**Comment by sudheeshkatkam** [comment]
The update does not handle all type (because some types were out of scope). The [latest patch](https://github.com/sudheeshkatkam/drill/commits/limit_zero) (WIP) is rebased on top of Hsuan's work.

**Comment by ilooner** [comment]
It looks like a commit for DRILL-3623 was already merged from PR https://github.com/apache/drill/pull/405 . So I am closing this.

**Pull request closed without merging**
