### PR TITLE
DRILL-3987: Componentize Drill, extracting vectors as separate library

### PR DESCRIPTION
**Pull request by jacques-n**
You can review the proposed separation steps here: 

https://docs.google.com/presentation/d/1HD-EzAgNe4EJvoP91ILFLFJdFjT2T5yfM9MEv79BaiM/edit

### CODE REVIEW

**Comment by adeneche** [comment]
This will heavily affect the allocator work. When do you plan to get this merged ?

**Comment by cwestin** [comment]
The allocator patch, which was only half this many files, and which was claimed to be too big, is almost all in. We're down to the last two of the many broken up patches. I think this patch should wait for that.

**Comment by jacques-n** [comment]
It seems like there are two points that Chris is asking about:

1) The scale of this patch (is it too big?)
2) The order of application between this patch and other patches (such as the allocator patch)

On (1): other than moving files, there are virtually no functional changes in this patch and its purpose is extremely narrow in scope. (There are probably six or so separations between interface and implementation.) Yes, there are a lot of files that were moved. The patch creates five new modules and has to move the appropriate files into those directories. All changes were focused on the same purpose of modularization. I also chose to limit any refactoring required in these patches exactly to avoid this challenge. (Note the orange lines that I deferred in the attached PPT). As such, I think it is unfair to characterize a modularization patch by counting the number of files that were involved. 

On (2): We typically order things in the order that they are ready to be merged. If this is a reasonable patch and is ready to be merged, it should be merged. If another patch has been reviewed, passes functional (and performance regression as appropriate) and is ready to be merged, it should be. In general, patches that are ready are ahead of patches that aren't ready.

Specifically on the allocator patch, on numerous occasions we have held up commits to master (and releases) to try get the allocator patch merged. On each occasion, we've found that it isn't ready to be merged due to concurrency design challenges. Let's address those before worrying about staging of the patch. Once we get the algorithm right and everyone has signed off on that, we can figure out rebasing on master and staging in relationship to other patches.

**Comment by parthchandra** [comment]
In general the patch looks fine.  I'm not sure I follow the reason for the drill-logical package.
My one concern was similar to Hakim's that this would affect the allocator changes quite a bit (and I think the allocator changes add more value). Can we split the changes? @adeneche can you comment on what changes would make it easier for you to merge?
BTW, master has moved and there is a merge conflict (easily resolved).

**Comment by jacques-n** [comment]
It is hard to respond to the value of the different allocator changes and their impact since I'm not sure where the patch is. Can you guys post the patch/Jira numbers and give a more detailed overview of their status? I understand DRILL-3940 encapsulates one of these changes. I just added some comments there as it seems like maybe it is a change based on DRILL 0.9 and doesn't consider some of the changes of DRILL 1.0.

**Comment by cwestin** [comment]
I've sent you the location of the branch many times; the remaining changes are still there: https://github.com/cwestin/incubator-drill/tree/alloc . After DRILL-3940 is merged (and then rebased back into that branch), it would be down the last 30 files, which I don't think would be easily broken down into any more smaller patches. These changes collectively found a number of bugs, which I fixed over time. They would also prevent more of the same kind in the future. I don't understand how it can appear to be based on Drill 0.9 when it was rebased just about a month ago, on 1.2.

**Comment by cwestin** [comment]
On 2.2 above: This description of events is not entirely accurate. We have never held up releases for the allocator work. Not once, never mind numerous occasions. For two releases during which it was not ready, I constructed special extract patches that included bug fixes only, because we believed it
would help the project. I did ask for people to hold off commits exactly once, for 24 hours. And once I found a problem (the rebase didn't go well), I took the hold off after about 18 hours.

As for merging patches in the order they are ready: the original allocator patch was ready about 3 months ago now. All the tests passed. The problem was that you refused to review it because it was too large. It was 213 files, less than half the size of this patch. Much like this one, there were "virtually no functional changes in this patch and its purpose is extremely narrow in scope." A large number of files had minor fixes that removed warnings, because these were helpful in finding bugs (biggest example: making a number of things AutoCloseables because then the compiler tells you when you leak resources -- this found a number of problems). The core changes are in about a dozen files, mainly the rewrite of the allocator itself.

You asked, and I pointed you at those core changes. I heard nothing back for a while, until you eventually asked that I break it up into smaller patches -- but still no comments on the allocator itself. Because of the layers of changes and dependencies, that was painful, but I did break things up. The first four were ready for review in mid-August. We exchanged messages and I told you where they were; When I came back from vacation in September, they had still not been reviewed. I made a stink at MapR, and some people finally reviewed them. I continued making patches (several more) which I continued to have a hard time getting people to review. When you finally did look at one, you immediately rejected it just because it didn't have its own JIRA. I submitted a JIRA for it within an hour of that, and it, like the others, continued to be ignored. I finally badgered more folks at MapR to review them.

Exactly once (not "numerous" times), at the time we ran the performance regression (a magical thing that only folks at MapR can do), we found that there is a performance penalty. I wouldn't call it a "concurrency design challenge." Yes, when you synchronize variables to get transacted behavior (memory allocation is really a balance transfer), instead of just depending on volatile variables that can change under your feet if you refer to them more than once, things are going to be slower. But you can do more.

In order to avoid this continual rebasing to track the project, I went back and made it possible for the new and old allocators to co-exist, so that the code would at least be committed while the performance penalty could be addressed (in order to avoid more rebasing in the future). This would also allow the use of the new allocator when assertions are enabled (or another debug flag), so that we could find any new problems; many of my rebases took time because I kept finding new problems introduced by ongoing work because the new allocator is much stricter than the old one.

You insisted that if others could just look at it, you were sure that a faster solution would be found; you asked for pointers to the code. I gave them to you. I never heard anything back. In any case, it is set up to only be used in debug mode for the moment, and can stay that way until someone can find a way to make it faster (and I explained the multiple implementations I tried before I finally got it down to the ~10% performance penalty it currently carries)

I continued breaking things down in an attempt to get them in. We are finally down to the last two patches.

Now I see a larger patch with the same characteristics, and it feels like it is being bulldozed through, even though there aren't clear benefits to having it. Your diagrams doesn't justify it, nor explain why it will be better. The new allocator, even if only used in debug mode for now, will help engineers avoid creating new leaks that the old allocator doesn't detect. Given some other suggestions I've seen to change the vector class interfaces, it seems like they're not stable enough to be broken out into a separate project yet; that will complicate changes.

**Comment by jacques-n** [comment]
Hey Chris, let's move this discussion to the pull request and/or patches that you're talking about. It is clear that you're frustrated that your allocator branch hasn't yet received a +1. Let's discuss it in the context of the changes themselves. DRILL-3940 is mentioned above and I have provided feedback on that JIRA. What other patches/pull requests and JIRAs do you feel like are ready to be merged that we can discuss in a more concrete manner?

**Comment by cwestin** [comment]
And I responded to the feedback on JIRA-3940, wherein I disagree with your comments; are you saying your word is final there?

After that one, there would be one more, which hasn't been put together yet, because it will want to be the alloc branch rebased (one more time?) with the 3940 changes (along with some of the other patches that have already gone in) merged. With that rebase, that one should be down to about 30 files, which include the core allocator changes, which haven't changed in the past few months.

**Comment by jacques-n** [comment]
I didn't see the comment on DRILL-3940. Will take a look.

**Comment by parthchandra** [comment]
Let's keep the discussion on DRILL-3940 out of this pull request and take it offline. For this patch, I see the changes as mostly benign.

**Comment by parthchandra** [comment]
+1 on this pull request. Allocator changes will have to be made on top of this ( @jacques-n, @adeneche are taking care of the allocator merging)

**Pull request closed without merging**
