### PR TITLE
Website update for 1.18.0

### PR DESCRIPTION
**Pull request by Agirish**

### CODE REVIEW

**Comment by cgivre** [comment]
@Agirish 
Thanks for doing this.  You might want to add the Druid plugin to the release notes: (https://github.com/apache/drill/pull/1888).  Also there was a format plugin for SPSS files.

**Comment by gdubya** [comment]
SPSS Format plugin: https://issues.apache.org/jira/browse/DRILL-7716

**Comment by cgivre** [comment]
@Agirish 
Any update on this?  I'd like to commit this soon. 
Thx!

**Comment by cgivre** [comment]
Let's get this done.. 
+1

**Pull request merged**
