### PR TITLE
DRILL-7960: Column metadata DECIMAL precision can exceed max supported value

### PR DESCRIPTION
**Pull request by jnturton**
# [DRILL-7960](https://issues.apache.org/jira/browse/DRILL-7960): Column metadata DECIMAL precision can exceed max supported value.

## Description
The calculation of the decimal precision needed to encompass two input decimal precisions and scales can produce precisions greater than the maximums supported by Drill. While this does not affect the output vector itself, it does cause the error reported in the associated Jira if column metadata to be included with the result data is built using org.apache.drill.exec.record.metadata.MetadataUtils, as is done for queries sent over the REST interface. This PR limits the calculated precision to the maximum supported value when this happens and log a precision loss warning.

## Documentation
N/A

## Testing
Manually run the repro query provided in the Jira.
New unit test TestTupleSchema:testDecimalWidening()

### CODE REVIEW

**Review by vvysotskyi — COMMENTED** [review]
Could you please add a unit test for the bug is fixed?

**Comment by jnturton** [comment]
> Could you please add a unit test for the bug is fixed?

@vvysotskyi, added.

**Comment by vvysotskyi** [comment]
@jnturton, I meant the test case that reproduces the issue from the ticket, when an error is thrown during creating a row set with results of the query execution. It is also possible that we have other places which should be updated.

**Comment by vvysotskyi** [comment]
Yes, please add such a test. We have test methods that allow obtaining row set for query results. Doesn't this issue is reproduced when they are used?

**Comment by jnturton** [comment]
> Yes, please add such a test. We have test methods that allow obtaining row set for query results. Doesn't this issue is reproduced when they are used?

If I correctly understand the test you intend (my implementation is shown below) then the answer is that it does not reproduce the issue...

```
  @Test
  public void testWideningLimit() throws Exception {
    String query = "SELECT CAST(10 AS DECIMAL(38, 4)) AS `Col1` UNION ALL SELECT CAST(22 AS DECIMAL(29, 6)) AS `Col1`";

    testBuilder().sqlQuery(query)
      .unOrdered()
      .baselineColumns("Col1")
      .baselineValues(new BigDecimal("10"))
      .baselineValues(new BigDecimal("22"))
      .go();
      
    List<Pair<SchemaPath, TypeProtos.MajorType>> expectedSchema = Collections.singletonList(Pair.of(
        SchemaPath.getSimplePath("Col1"),
        Types.withPrecisionAndScale(MinorType.VARDECIMAL, DataMode.REQUIRED, 38, 6)));

    testBuilder()
        .sqlQuery(query)
        .schemaBaseLine(expectedSchema)
        .go();
  }
```

**Comment by jnturton** [comment]
> If I correctly understand the test you intend (my implementation is shown below) then the answer is that it does not reproduce the issue...

Ignore this, I just hadn't run things properly locally! The proposed SQL test does catch the issue in the schema validation step. Thanks for the help.

**Review by vvysotskyi — APPROVED** [review]
Thanks for making changes, +1

**Pull request merged**
