### PR TITLE
DRILL-8415: Upgrade Jackson 2.14.3 → 2.16.1

### PR DESCRIPTION
**Pull request by jnturton**
# [DRILL-8415](https://issues.apache.org/jira/browse/DRILL-8415): Upgrade Jackson 2.14.3 → 2.16.1

## Description

The following should be investigated before merging.

> There are some security focused enhancements including a new class called StreamReadConstraints. The defaults on [StreamReadConstraints](https://javadoc.io/static/com.fasterxml.jackson.core/jackson-core/2.15.0-rc1/com/fasterxml/jackson/core/StreamReadConstraints.html) are pretty high but it is not inconceivable that some Drill users might need to relax them. Parsing large strings as numbers is sub-quadratic, thus the default limit of 1000 chars or bytes (depending on input context).
> 
> When the Drill team consider upgrading to Jackson 2.15 or above, you might also want to consider adding some way for users to configure the StreamReadConstraints.

## Documentation
N/A

## Testing
Unit tests pass.

### CODE REVIEW

**Comment by Lceeba** [comment]
Unsubscribe

**Review by cgivre — APPROVED** [review]
LGTM +1 (Pending CI)

**Comment by jnturton** [comment]
I starting adding congifuration support for the new StreamReadConstraints, first globally and then just in the JSON reader, but I got stopped by a sense of YAGNI. It's hard to imagine someone who will need something beyond the default values in Jackson and more configuration is more complexity that users must contend with. So my opinion at this point is that we should only add that configurability if someone asks for it...

**Comment by cgivre** [comment]
@jnturton This looks good however there is a merge conflict.   Can you please resolve so that we can run the CI?

**Comment by jnturton** [comment]
I haven't rebased this yet in case we decide to squash the WIP commits that were merged into master. Once a decision is made either way this can be rebased and a CI run obtained.

**Comment by cgivre** [comment]
> I haven't rebased this yet in case we decide to squash the WIP commits that were merged into master. Once a decision is made either way this can be rebased and a CI run obtained.

I'm fine with leaving the WIP commits as long as we don't make a habit out of it.  It's probably more of a hassle to undo the PR, squash the commits and re-merge them.

**Pull request merged**
