### PR TITLE
DRILL-5704: Improve error message on client side when queries fail wi…

### PR DESCRIPTION
**Pull request by sohami**
…th "Failed to create schema tree." when Impersonation is enabled and logins are anonymous

### CODE REVIEW

**Comment by priteshm** [comment]
@parthchandra can you please review this?

**Comment by parthchandra** [comment]
This is only marginally better. It would be nicer if the error message could suggest what the user needs to do to fix the problem, perhaps?

**Comment by sohami** [comment]
@parthchandra - Thanks for the feedback. IOException is thrown for various reason from FileSystem api's and hence I was just printing the exception message. But I have added a hint statement based on impersonation case specifically. Now it will print like below.

Error: RESOURCE ERROR: Failed to create schema tree.

IOException:  Error getting user info for current user, anonymous
_[Hint: Username is absent in connection URL or doesn't exist on Drillbit node. Please specify a username in connection URL which is present on Drillbit node.]_

[Error Id: 1cf76f0f-28d0-4fda-93bd-e7c03a0088d3 on qa-node164.qa.lab:31010] (state=,code=0)

**Comment by parthchandra** [comment]
+1

**Comment by paul-rogers** [comment]
@sohami, please rebase on latest master and resolve conflicts.

**Comment by sohami** [comment]
This PR was already merged by @arina-ielchiieva on 08/24

**Pull request closed without merging**
