### PR TITLE
Drill 4581

### PR DESCRIPTION
**Pull request by paul-rogers**
Provides fixes to the Drill launch scripts for multiple issues in DRILL-4581.

### CODE REVIEW

**Comment by jacques-n** [comment]
A quick question and an fyi. (I haven't looked at the details of the patch.)

q) Does this change the external interface of the scripts. If so, we should probably put in the v2 branch.
fyi) In general: you should make sure that your patch is rebased as opposed to merge.

**Comment by paul-rogers** [comment]
This fix leaves the external interface unchanged. This is a preparation for the work to add a site configuration level; but none of that work is in this fix. Instead, this particular fix just corrects problems in the existing public interface. I ran tests to ensure that the scripts continue to work as before where they worked, but they now work properly where the previous version was broken.

Thanks for the comment on merge; I expected I'd miss something on this first checkin...

**Comment by jacques-n** [comment]
Once you've gone through reviews, you should also collapse your change into a single commit and name it using the pattern below. This allows a committer to make sure to get everything right.

DRILL-XXXX: short description

Longer description...

**Comment by paul-rogers** [comment]
Thanks; I'll do that.

**Comment by paul-rogers** [comment]
Closing this request due to some newbie Git errors. Will open a new one in proper format.

**Pull request closed without merging**
