### PR TITLE
DRILL-8420: Remove Guava shading and patching

### PR DESCRIPTION
**Pull request by jnturton**
# [DRILL-8420](https://issues.apache.org/jira/browse/DRILL-8420): Remove Guava shading and patching.

## Description

Based on #2782 to enable a clean CI run.

- Remove shaded Guava.
- Drop Guava patches.
- Upgrade guava to 31.1-jre.

## Documentation

N/A

## Testing

Existing unit tests.

### CODE REVIEW

**Comment by cgivre** [comment]
@jnturton Thanks for this.  Aside from imports, which files were actually modified and I'll do a review?

**Comment by cgivre** [comment]
Do we want to add this to back port to stable?

**Comment by jnturton** [comment]
@cgivre 

> Thanks for this. Aside from imports, which files were actually modified and I'll do a review?

Yes, I'll split the import statement changes into a separate commit.

> Do we want to add this to back port to stable?

I don't think so. It's not a fix and it definitely carries a risk of breakage with it. Currently the Hadoop 2 build is broken because Drill's Guava patches (but not shading) are still needed in that case so I'll set the PR to draft for the moment.

**Comment by cgivre** [comment]
@jnturton Is this PR still relevant?

**Comment by jnturton** [comment]
> @jnturton Is this PR still relevant?

Yes, I'm going to resurrect it after all the other clean up and upgrade PRs are in.

**Pull request closed without merging**
