### PR TITLE
DRILL-4124: Make all uses of AutoCloseables use addSuppressed exceptions to avoid noise in logs

### PR DESCRIPTION
**Pull request by julienledem**

### CODE REVIEW

**Comment by jaltekruse** [comment]
+1

**Comment by julienledem** [comment]
Thanks @jaltekruse ! Did you mean to commit this?

**Comment by jaltekruse** [comment]
I put it on my merge branch but it actually caused two small compilation issues in other modules that were using the utility method you refactored. I forgot to update this with a comment.

**Comment by julienledem** [comment]
Thanks for the heads up. I will fix this.

**Comment by julienledem** [comment]
@jaltekruse should be better now :)

**Pull request closed without merging**
