### PR TITLE
DRILL-4159: Use test framework in TestCsvHeader

### PR DESCRIPTION
**Pull request by StevenMPhillips**

### CODE REVIEW

**Comment by vkorukanti** [comment]
+1

**Comment by StevenMPhillips** [comment]
I didn't do a full build with tests before merging, and it looks like there is a checkstyle problem.
I fixed it, and am now doing a full build to verify before merging.

**Comment by jaltekruse** [comment]
As long as you are changing it do you want to remove the two test classes still using this method and then just delete it?

**Comment by StevenMPhillips** [comment]
Which method?

**Comment by jaltekruse** [comment]
The one that is generating a string representation of the result set, which caused the bug. getResultString()

**Pull request merged**
