### PR TITLE
DRILL-4474: Use varchar for default column when all_text_mode is enab…

### PR DESCRIPTION
**Pull request by amansinha100**
…led.

### CODE REVIEW

**Comment by jacques-n** [comment]
Can you generate the test file as part of the test rather than check in static?

**Comment by amansinha100** [comment]
Yes, I can do that.

**Comment by jaltekruse** [comment]
Could you also close this PR and open a new one? the JIRA number was wrong in your commit so this is posting to the JIRA about incorrect creation if direct scans. The correct number is 4479

**Comment by amansinha100** [comment]
oops ... sorry, closing this and will reopen against the correct JIRA.

**Pull request closed without merging**
