### PR TITLE
DRILL-7270 Changed URLs from HTTP to secure HTTPS links and added checksums

### PR DESCRIPTION
**Pull request by DanielT504**
# [DRILL-7270](https://issues.apache.org/jira/browse/DRILL-7878): Changed URLs from HTTP to secure HTTPS links and added checksums

## Description
Changed links from HTTP to HTTPS to fix LGTM errors, and added checksums in cooperation with DRILL-7270 (https://issues.apache.org/jira/browse/DRILL-7270) .  

This PR is a subtask of 
* DRILL-7878 (https://github.com/apache/drill/pull/2187)

## Documentation
No user facing changes.

## Testing
Made sure updated URLs were still supported.

### CODE REVIEW

**Comment by cgivre** [comment]
@DanielT504 
I tried accessing https://onejar-maven-plugin.googlecode.com/svn/mavenrepo and https://scala-tools.org/repo-releases and both seem to be unavailable.   Can you please verify which dependencies actually use these repos and if none, can we remove them all together?  I tried both `http` and `https` and neither seemed to work. 
Thanks!

**Comment by DanielT504** [comment]
> @DanielT504
> I tried accessing https://onejar-maven-plugin.googlecode.com/svn/mavenrepo and https://scala-tools.org/repo-releases and both seem to be unavailable. Can you please verify which dependencies actually use these repos and if none, can we remove them all together? I tried both `http` and `https` and neither seemed to work.
> Thanks!

Good point, I've removed those ones entirely.

**Review by cgivre — APPROVED** [review]
LGTM +1

**Comment by cgivre** [comment]
@DanielT504 
I approved this, but can you take a look at some of the `pom.xml` files in the `contrib` folder to see if there are any other repos that use `http`?  Assuming this passes CI, we are good to go. 
Thanks for the contribution!!

**Comment by DanielT504** [comment]
> @DanielT504
> I approved this, but can you take a look at some of the `pom.xml` files in the `contrib` folder to see if there are any other repos that use `http`? Assuming this passes CI, we are good to go.
> Thanks for the contribution!!

I will, thank you!

**Review by vvysotskyi — CHANGES_REQUESTED** [review]
@DanielT504 please take a look at https://issues.apache.org/jira/browse/DRILL-7270 and the branch attached in the comments and please cooperate with those changes if possible.

**Comment by DanielT504** [comment]
> @DanielT504 please take a look at https://issues.apache.org/jira/browse/DRILL-7270 and the branch attached in the comments and please cooperate with those changes if possible.

I'm not sure I fully understand what you are requesting. Should I make a different PR for that issue instead?

**Comment by vvysotskyi** [comment]
That ticket has a link to unfinished changes (that also includes changes you made in this PR). I propose to complete those changes in the scope of this PR.

**Comment by DanielT504** [comment]
> That ticket has a link to unfinished changes (that also includes changes you made in this PR). I propose to complete those changes in the scope of this PR.

There appears to be changes in that ticket that involve checksum-checks, not just non-https URLs. Should I include all of these changes in my new PR, or just the ones involving non-https URLs?

**Comment by vvysotskyi** [comment]
The checksum checks are also nice to have. Please ensure that the authorship of the commits you use will be preserved
https://docs.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors

**Comment by luocooong** [comment]
@cgivre @vvysotskyi Hello. I try to using the following commands on my local, But had not found any jar related to the above repository. So, Is there any new revision suggestions? Or ready to merge it?
 1. the output if using a repository. eg `jitpack.io` :
```
find /Users/luoc/.m2/ -name _remote.repositories |xargs grep -ri "jitpack.io" -l
/Users/luoc/.m2//repository/com/github/vvysotskyi/drill-calcite/calcite/1.21.0-drill-r2/_remote.repositories
/Users/luoc/.m2//repository/com/github/vvysotskyi/drill-calcite/calcite-core/1.20.0-drill-r2/_remote.repositories
...
```
2. no output with the `onejar-maven-plugin.googlecode.com` and `scala-tools.org` :
```
find /Users/luoc/.m2/ -name _remote.repositories |xargs grep -ri "onejar-maven-plugin.googlecode.com" -l

```

**Comment by vvysotskyi** [comment]
Hi @luocooong, no, it is not ready. Please see my comments above regarding cooperating with changes from another ticket...

**Comment by DanielT504** [comment]
> The checksum checks are also nice to have. Please ensure that the authorship of the commits you use will be preserved
> https://docs.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors

It seems that dgrinchenko does not have a public email for me to link for co-authorship, and I have no way to contact him. How should I proceed with the changes?

**Comment by cgivre** [comment]
@DanielT504 
How's it going?  I was on vacation last week, but where are we on this PR?

**Comment by DanielT504** [comment]
> @DanielT504
> How's it going? I was on vacation last week, but where are we on this PR?

No problem, I have made the changes @vvysotskyi asked for, and credited @dgrinchenko as co-author. 2 of the Git CI tests simply timed out after the 90 minute limit, which leads me to believe that there is no issue with what I changed (since I only updated pom.xml files and they would have failed the checks much sooner), but I am not certain.

**Comment by cgivre** [comment]
@DanielT504 
Can you please rebase with current master so that we can merge this PR?
Thx!

**Comment by DanielT504** [comment]
> @DanielT504
> Can you please rebase with current master so that we can merge this PR?
> Thx!

I had some complications because I had to revert a revert to mend a prior error on my part. Could you double check that this is what you were asking for?

**Comment by luocooong** [comment]
@cgivre @DanielT504 It seems that this PR is related to an umbrella JIRA (DRILL-7878). So, It better to convert this PR as a new sub-task for the DRILL-7878 (It no longer represents the 7828)? Maybe it can speed up the merge for this PR.

**Comment by DanielT504** [comment]
@luocooong Just to be clear, does this just mean creating another JIRA subtask, then editing the PR description and commit titles to match the ticket code?

**Comment by cgivre** [comment]
> @luocooong Just to be clear, does this just mean creating another JIRA subtask, then editing the PR description and commit titles to match the ticket code?

This is just done in JIRA.  I'll merge this tomorrow morning unless there are any objections.

**Comment by DanielT504** [comment]
@cgivre none from me, thank you!

**Pull request merged**
