### PR TITLE
DRILL-6712: Creation of jdbc storage plugin fails with NoSuchMethod

### PR DESCRIPTION
**Pull request by oleg-zinovev**
Update of commons-pool2 dependency

### CODE REVIEW

**Comment by arina-ielchiieva** [comment]
Should we try to upgrade to the latest version (https://mvnrepository.com/artifact/org.apache.commons/commons-pool2)?

**Comment by oleg-zinovev** [comment]
"The job exceeded the maximum time limit for jobs, and has been terminated. "
What can i do with this error?

**Comment by arina-ielchiieva** [comment]
It happens, just restart the build but I am sure if you have permission (so I'll do it for you).

**Comment by oleg-zinovev** [comment]
Same error.
I do not have permissions to restart build :(

**Comment by arina-ielchiieva** [comment]
@oleg-zinovev restarted the build one more time, though it was failed log showed that it has passed successful but failed in the end, so it's critical, happens sometimes with Travis.
Also still waiting your feedback about upgrading to 2.6 instead of 2.5.

**Comment by oleg-zinovev** [comment]
I do not see any breaking changes in version 2.6.0 (https://commons.apache.org/proper/commons-pool/changes-report.html#a2.6.0), so it's really better to upgrade to the latest version

**Comment by arina-ielchiieva** [comment]
+1, LGTM. @oleg-zinovev thanks for the PR.

**Pull request closed without merging**
