### PR TITLE
DRILL-7851: Restore original and untruncated license text

### PR DESCRIPTION
**Pull request by pombredanne**
# [DRILL-7851](https://issues.apache.org/jira/browse/DRILL-7851): Restore original and untruncated license text

## Description
The original MIT license text is truncated. This restores the broken text.
See https://storage.googleapis.com/google-code-archive-source/v2/code.google.com/y2038/source-archive.zip for details.
Found during a scan with https://github.com/nexB/scancode-toolkit

Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

## Documentation
NA

## Testing
NA

### CODE REVIEW

**Comment by pombredanne** [comment]
Note that there is another possible issue wrt. licenses.
The original code from Paul Sheer was under a different license found at
https://web.archive.org/web/20100425004934/http://www.2038bug.com/pivotal_gmtime_r.c.html
>    Redistribution and use in source form, with or without modification,
   is permitted provided that the above copyright notice, this list of
   conditions, the following disclaimer, and the following char array
   are retained.

 >  Redistribution and use in binary form must reproduce an
   acknowledgment: 'With software provided by http://2038bug.com/' in
   the documentation and/or other materials provided with the
   distribution, and wherever such acknowledgments are usually
   accessible in Your program.

>   This software is provided "AS IS" and WITHOUT WARRANTY, either
   express or implied, including, without limitation, the warranties of
   NON-INFRINGEMENT, MERCHANTABILITY or FITNESS FOR A PARTICULAR
   PURPOSE. THE ENTIRE RISK AS TO THE QUALITY OF THIS SOFTWARE IS WITH
   YOU. Under no circumstances and under no legal theory, whether in
   tort (including negligence), contract, or otherwise, shall the
   copyright owners be liable for any direct, indirect, special,
   incidental, or consequential damages of any character arising as a
   result of the use of this software including, without limitation,
   damages for loss of goodwill, work stoppage, computer failure or
   malfunction, or any and all other commercial damages or losses. This
   limitation of liability shall not apply to liability for death or
   personal injury resulting from copyright owners' negligence to the
   extent applicable law prohibits such limitation. Some jurisdictions
   do not allow the exclusion or limitation of incidental or
   consequential damages, so this exclusion and limitation may not apply
   to You.

... which looks OK on the surface but is not an MIT or BSD proper and not the MIT at issue here for sure.

**Review by cgivre — APPROVED** [review]
LGTM +1

**Comment by cgivre** [comment]
@pombredanne 
Can you please open a pull request at https://issues.apache.org?  Once that is opened, please put the issue number (DRILL-XXXX) in the title of the PR and the commit message.
Thanks!

**Comment by luocooong** [comment]
@cgivre All done.

**Pull request merged**
