### PR TITLE
DRILL-4006: Ensure the position of MapWriters is set

### PR DESCRIPTION
**Pull request by hsuanyi**
This can help eliminate potential IOOB exception

### CODE REVIEW

**Comment by StevenMPhillips** [comment]
I think the fix is in the wrong place. We should fix the underlying vector. I was able to fix the problem with a small change to BaseRepeatedValueVector.BaseRepeatedMutator:

```java
@Override
    public void startNewValue(int index) {
      while (offsets.getValueCapacity() <= index) {
        offsets.reAlloc();
      }
      offsets.getMutator().setSafe(index+1, offsets.getAccessor().get(index));
      setValueCount(index+1);
    }
```

We shouldn't need to make any change in the writer.

**Comment by hsuanyi** [comment]
You mean the DRILL-4032?

**Comment by StevenMPhillips** [comment]
No, I'm talking about this issue. The problem is not really with the writer, its in the underlying vector.

**Comment by hsuanyi** [comment]
Do you like to fix this issue or you like me to update my patch?

**Pull request closed without merging**
