### PR TITLE
DRILL-5229: update kudu-client to 1.3.0

### PR DESCRIPTION
**Pull request by eskabetxe**
update kudu-client to 1.3.0 and minor change to work properly

### CODE REVIEW

**Comment by sudheeshkatkam** [comment]
@eskabetxe thank you for the pull request!

How did you test the patch? I have not looked into the Kudu plugin before, but I noticed that the unit tests are [ignored by default](https://github.com/apache/drill/commit/aa39c66d92ec03c90f3715df7cc4fde49d76a334).

**Comment by eskabetxe** [comment]
Hi @sudheeshkatkam ,
I have a docker image with kudu. 
For "TestKuduConnect" we comment the @ignore and change the "KUDU_MASTER" for docker ip
(i realize that i havent push the change to work the test, done now)
For "TestKuduPlugin" we couldnt make the test work.. comment the @ignore and changing the file "bootstrap-storage-plugins.json" is giving this error:
"Could not resolve type id 'maprdb' into a subtype of [simple type, class org.apache.drill.common.logical.FormatPluginConfig]: known type ids"
And maprdb is not for kudu plugin..

This part we are testing under development and is working fine, we had some issues with strings values but this is fixed in last commit.


Regards

**Comment by sudheeshkatkam** [comment]
Can you post the complete error message?

**Comment by eskabetxe** [comment]
`java.lang.IllegalStateException: com.fasterxml.jackson.databind.JsonMappingException: Could not resolve type id 'maprdb' into a subtype of [simple type, class org.apache.drill.common.logical.FormatPluginConfig]: known type ids = [FormatPluginConfig, avro, httpd, json, named, parquet, sequencefile, text]
 at [Source: {
  "storage":{
    dfs: {
      type: "file",
      connection: "maprfs:///",
      workspaces: {
        "root" : {
          location: "/",
          writable: false
        },
        "tmp" : {
          location: "/tmp",
          writable: true,
          storageformat: "csv"
        }
      },
      formats: {
        "psv" : {
          type: "text",
          extensions: [ "tbl" ],
          delimiter: "|"
        },
        "csv" : {
          type: "text",
          extensions: [ "csv" ],
          delimiter: ","
        },
        "tsv" : {
          type: "text",
          extensions: [ "tsv" ],
          delimiter: "\t"
        },
        "parquet" : {
          type: "parquet"
        },
        "json" : {
          type: "json"
        },
        "maprdb" : {
          type: "maprdb"
        }
      }
    },

    cp: {
      type: "file",
      connection: "classpath:///",
      formats: {
        "json" : {
          type: "json"
        },
        "parquet" : {
          type: "parquet"
        }
      }
    }
  }
}
; line: 40, column: 17] (through reference chain: org.apache.drill.exec.planner.logical.StoragePlugins["storage"]->java.util.LinkedHashMap["dfs"]->org.apache.drill.exec.store.dfs.FileSystemConfig["formats"]->java.util.LinkedHashMap["maprdb"])

	at org.apache.drill.exec.store.StoragePluginRegistryImpl.createPlugins(StoragePluginRegistryImpl.java:185)
	at org.apache.drill.exec.store.StoragePluginRegistryImpl.init(StoragePluginRegistryImpl.java:128)
	at org.apache.drill.exec.server.Drillbit.run(Drillbit.java:122)
	at org.apache.drill.BaseTestQuery.openClient(BaseTestQuery.java:198)
	at org.apache.drill.BaseTestQuery.openClient(BaseTestQuery.java:186)
	at org.apache.drill.BaseTestQuery.setupDefaultTestCluster(BaseTestQuery.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Could not resolve type id 'maprdb' into a subtype of [simple type, class org.apache.drill.common.logical.FormatPluginConfig]: known type ids = [FormatPluginConfig, avro, httpd, json, named, parquet, sequencefile, text]
 at [Source: {
  "storage":{
    dfs: {
      type: "file",
      connection: "maprfs:///",
      workspaces: {
        "root" : {
          location: "/",
          writable: false
        },
        "tmp" : {
          location: "/tmp",
          writable: true,
          storageformat: "csv"
        }
      },
      formats: {
        "psv" : {
          type: "text",
          extensions: [ "tbl" ],
          delimiter: "|"
        },
        "csv" : {
          type: "text",
          extensions: [ "csv" ],
          delimiter: ","
        },
        "tsv" : {
          type: "text",
          extensions: [ "tsv" ],
          delimiter: "\t"
        },
        "parquet" : {
          type: "parquet"
        },
        "json" : {
          type: "json"
        },
        "maprdb" : {
          type: "maprdb"
        }
      }
    },

    cp: {
      type: "file",
      connection: "classpath:///",
      formats: {
        "json" : {
          type: "json"
        },
        "parquet" : {
          type: "parquet"
        }
      }
    }
  }
}
; line: 40, column: 17] (through reference chain: org.apache.drill.exec.planner.logical.StoragePlugins["storage"]->java.util.LinkedHashMap["dfs"]->org.apache.drill.exec.store.dfs.FileSystemConfig["formats"]->java.util.LinkedHashMap["maprdb"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:216)
	at com.fasterxml.jackson.databind.DeserializationContext.unknownTypeException(DeserializationContext.java:983)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:281)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:163)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:106)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:91)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:142)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:497)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:341)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:260)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:163)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:135)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:120)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:91)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:142)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:497)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:341)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:465)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:380)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1123)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:298)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:133)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3788)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2779)
	at org.apache.drill.exec.store.StoragePluginRegistryImpl.createPlugins(StoragePluginRegistryImpl.java:147)
	... 16 more
`

**Comment by eskabetxe** [comment]
attached
[error.txt](https://github.com/apache/drill/files/1023007/error.txt)

**Comment by sudheeshkatkam** [comment]
+1

The error seems unrelated to the changes, and all tests pass. Thank you for the PR!

**Pull request closed without merging**
