### PR TITLE
Drill-5834: Add Networking Functions

### PR DESCRIPTION
**Pull request by cgivre**
This is a collection of Networking Functions to facilitate network analysis.  The functions include:

- **inet_aton(`<ip>`)**:  Converts an IPv4 address into an integer.
- **inet_ntoa( `<int>`)**:  Converts an integer IP into dotted decimal notation
- **in_network( `<ip>`,`<cidr>` )**: Returns true if the IP address is in the given CIDR block
- **address_count( `<cidr>` )**:  Returns the number of IPs in a given CIDR block
- **broadcast_address( `<cidr>` )**: Returns the broadcast address for a given CIDR block
- **netmask(`<cidr>` )**: Returns the netmask for a given CIDR block. 
- **low_address(`<cidr>`)**:  Returns the first address in a given CIDR block.
- **high_address(`<cidr>`)**:  Returns the last address in a given CIDR block.
- **url_encode( `<url>` )**:  Returns a URL encoded string.
- **url_decode( `<url>` )**:   Decodes a URL encoded string.
- **is_valid_IP(`<ip>`)**: Returns true if the IP is a valid IP address
- **is_private_ip(`<ip>`)**: Returns true if the IP is a private IPv4 address
- **is_valid_IPv4(`<ip>`)**: Returns true if the IP is a valid IPv4 address
- **is_valid_IPv6(`<ip>`)**: Returns true if the IP is a valid IPv6 address

### CODE REVIEW

**Comment by cgivre** [comment]
@paul-rogers @arina-ielchiieva 
I'm terrible at git so here is a clean copy of the PR with one commit.

**Comment by arina-ielchiieva** [comment]
@cgivre actually, it's not a good idea to create new pull request. First of all we'll loose all comments history. Second, now during batch commits sometimes batch committer squashes the commits for the developer but when we'll move to the gitbox the developer will be responsible for squashing commits. If it's possible please reopen the old pull request and squash the commits or you can re-write your previous branch with this one. Anyway, I would really like if we'll use the initial pull request.

**Comment by cgivre** [comment]
@arina-ielchiieva 
I followed the instructions you sent and due to the force commit, it isn't possible to re-open the original PR.

**Comment by arina-ielchiieva** [comment]
Ok, please update the commit message, it should contain semicolon after Jira number.

**Comment by arina-ielchiieva** [comment]
Link to the original PR -  https://github.com/apache/drill/pull/971

**Comment by amansinha100** [comment]
@arina-ielchiieva if this is good to go, can you mark the JIRA as read-to-commit ?  I will squash the 3 commits that @cgivre has created and modify the commit message before committing.

**Comment by arina-ielchiieva** [comment]
Aman, thanks for agreeing to squash the commits. Marked Jira as ready-to-commit.

**Pull request closed without merging**
