### PR TITLE
DRILL-4203: fix dates written into parquet files to conform to parquet format spec

### PR DESCRIPTION
**Pull request by jaltekruse**
This branch includes an update of the version number to 1.5.0, this is required because we need a hard release to signal that all future parquet files are not corrupted. Without this change the fixed files written by the writer would still be considered corrupt (as all of the rest of the files generated with earlier commits with the version 1.5.0-SNAPSHOT will actually be corrupted). This commit can be removed/amended when the changes are merged, but this patch should be immediately followed by a change of the version number to avoid the risk of generating files with corrected date values, but a version number that will tell the reader to still shift the dates.

### CODE REVIEW

**Comment by jaltekruse** [comment]
@adeneche @parthchandra @StevenMPhillips Can one of you please review this change?

**Comment by adeneche** [comment]
@jaltekruse why the version change ?

**Comment by jaltekruse** [comment]
Did you see my comment above? I am using the version number to signal that the dates are fixed now and in all future versions. All other commits with a version of 1.5.0-SNAPSHOT have produced invalid date values, so I want to make sure we correct dates in files that have the current version string written into their footers.

**Comment by jaltekruse** [comment]
This has been replaced by 
https://github.com/apache/drill/pull/595

**Pull request closed without merging**
