### PR TITLE
Adding powered by page with initial set of companies

### PR DESCRIPTION
**Pull request by aashreya**

### CODE REVIEW

**Comment by aashreya** [comment]
@kkhatua and @bbevens

**Comment by kkhatua** [comment]
@aashreya  can you add the screenshots in the PR? 
@bbevens please do a review, since I am not familiar with the templating engine and might miss something if I commit it myself.

**Comment by aashreya** [comment]
screen shot 2019-02-25 at 2 01 43 pm

**Comment by aashreya** [comment]
screen shot 2019-02-25 at 2 02 03 pm

**Pull request merged**
