### PR TITLE
DRILL-8009: DrillConnectionImpl#isValid() doesn't correspond JDBC API

### PR DESCRIPTION
**Pull request by rymarm**
# [DRILL-8009](https://issues.apache.org/jira/browse/DRILL-8009): DrillConnectionImpl#isValid() doesn't correspond JDBC API

## Description

I've add ping function which send message with [RpcMode.PING](http://drill.apache.org/apidocs/org/apache/drill/exec/proto/GeneralRPCProtos.RpcMode.html#PING) to drillbit and after that waits for a response message with [RpcMode.PONG](drill.apache.org/apidocs/org/apache/drill/exec/proto/GeneralRPCProtos.RpcMode.html#PONG). This method is used to validate connection. I add this verification to [DrillConnectionImpl#isValid(int timeout)](https://github.com/apache/drill/blob/5f5ae89392471d237605c0b5e1a337e5bc0e10ff/exec/jdbc/src/main/java/org/apache/drill/jdbc/impl/DrillConnectionImpl.java#L522) as it is required by JDBC API [documentation](https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/Connection.html#isValid(int)) and gives opportunity accurately validate connection:

>  The driver shall submit a query on the connection or use some other mechanism that positively verifies the connection is still valid when this method is called

Also, I've add to [DrillConnectionImpl#isValid(int timeout)](https://github.com/apache/drill/blob/5f5ae89392471d237605c0b5e1a337e5bc0e10ff/exec/jdbc/src/main/java/org/apache/drill/jdbc/impl/DrillConnectionImpl.java#L522) simple check for [channel#isActive()](https://netty.io/4.1/api/io/netty/channel/Channel.html#isActive--).

[Previously, in Drill](https://github.com/apache/drill/commit/960f876a1945eee4eeb0d6a98c5c58dfe2eea1a9) were add `PING` and `PONG` RpcMode's, but they was primarily used for "hearbeat" function — to let drillbit know, that connection with client is still alive and now I also used it for client verification of connection to drillbit.

I've used listener pattern for checking whether client got `PONG` answer or not. If you think, that this realization is not best, I have ideas how it can be implemented in other, more "netty's" way.

## Documentation
No doc impact

## Testing
Manual tests with cases:
* server (drillbit) closes connection
* server (drillbit) shut down
* server (drillbit) process has been killed
* client (jdbc) lost network connection
* client (jdbc) temporary lost connection and restored it until JDBC's ping timeout has been elapsed.

### CODE REVIEW

**Comment by luocooong** [comment]
@rymarm Hello. Could you please do a rebase on the master branch ?
We just submitted a quick fix patch for the maven build.

**Comment by rymarm** [comment]
@luocooong Thank you for remind! I've made rebase.

**Comment by luocooong** [comment]
@rymarm Thanks for the feedback. I will check it on the local and let you know.

**Comment by paul-rogers** [comment]
Hi @rymarm, thanks for the contribution!

Your description mentions that the Drill RPC already sends heartbeats. Here is some background.

For systems such as MySQL, the connection to the server can remain open, but idle if no queries are sent. At some point, the MySql server will close the connection due to inactivity. The client won't know this until it tries to take some action. In this case, `isValid()` makes sense: it sends something to see if anyone is still on the other end.

In Drill's case, there is always the heartbeat, so the connection will never timeout from disuse, only from a network failure or because the server failed. So, the client always knows that the connection is still valid (or was at the time of the last heartbeat. We can check how frequently they occur; I think it is on the order of 30 seconds or so, but I may be wrong.)

The Drill JDBC connection uses Drill's native home-grown Netty-based RPC mechanism. That mechanism includes keep-alive heartbeats. On servers, each Drillbit sends the Ping/Pong messages to each other to verify that the Drillbits are still up. In fact, in the old days, somethings things would fail under heavy load because the CPU was so busy that the heartbeat thread didn't get a chance to run, and the connection was assumed failed.

The Ping/Pong messages occur over the same channel as the data flow. We had cases where the client was slow to read data, and thus a heartbeat message was backed up behind data batches and the connection ended up failing as a result. I don't recall how we resolved that. Did we disable heartbeat for clients? Move heartbeat to the control channel?

Given all this, the extra work in `isValid()` is not as necessary as it is with other systems such as MySQL. Still, no harm in adding an extra check. So, the question is, does the `isValid()` method need to know the state at this exact instant? Or, is it good enough to know that the connection was OK when we last checked 30 seconds (or whatever) ago? Either way, we'll keep checking in the background whether the client asks or not.

What do you think?

**Comment by rymarm** [comment]
@paul-rogers Hello! Could you, please, review my fix? I've rewritten my previous code totally and made it in "netty style" to make it thread-safe, extensible and simple to understand.

Besides this, I've also:
- corrected `DrillConnectionImpl#close()` so it worked correctly and could catch cases, when netty`s connection was closed;
- overrided  `AvaticaConnection#close()` in `DrillConnectionImpl` so it now correctly implement `Autocloseable` interface.

**Comment by rymarm** [comment]
@luocooong Hello! Can someone take a look at this PR? I pinged @paul-rogers but seems he is busy, it has passed 18 days since my remind.

**Comment by luocooong** [comment]
@rymarm Hello, sorry for the delay. Paul will take a look in the next couple of days.  The pull request is associated with the core module, Paul has the most powerful voice. Thank you for understanding.

**Comment by paul-rogers** [comment]
@rymarm & @luocooong sorry, I've been off on other stuff. Before I did into the code again, I'd like to check one thing. Suppose I build the new JDBC driver with this fix. Suppose I run it with a previously-released Drill that does not have the server-side fixes? Will it work? Or, does this JDBC driver require a matching server?

**Comment by rymarm** [comment]
@paul-rogers yes, JDBC driver will work with previously build server. Server handle PING request starting from Drill 1.0.0: https://github.com/apache/drill/commit/960f876a1945eee4eeb0d6a98c5c58dfe2eea1a9#diff-b22efd8eda87a1b49514aff0d3886c7f01a1ea0f6a914f7ad390b891d8adec25

**Review by paul-rogers — APPROVED** [review]
@rymarm thanks much for the revisions and especially for finding a way to make the change backward compatible.
LGTM +1

**Pull request merged**
