### PR TITLE
DRILL-5425: Support HTTP Kerberos auth using SPNEGO

### PR DESCRIPTION
**Pull request by sindhurirayavaram**
SPNEGO extends kerberos authentication to Drill WEB UI. 

Things to be added 
-Unit Tests
-Showing the login option depending on the configured mechanisms

### CODE REVIEW

**Comment by paul-rogers** [comment]
@sohami, can you review this one?

**Comment by sohami** [comment]
@sindhurirayavaram - Can you please resolve the merge conflict with master ?

**Comment by sohami** [comment]
Created a separate PR for this JIRA: https://github.com/apache/drill/pull/1040
1) I have kept the initial commit with the new PR and added new changes as separate commit.
2) Changes include refactoring of the code, added new tests and fixes done for the issues.

**Comment by arina-ielchiieva** [comment]
@sindhurirayavaram please close the pull request.

**Pull request closed without merging**
