### PR TITLE
DRILL-6733: Unit tests from KafkaFilterPushdownTest are failing in so…

### PR DESCRIPTION
**Pull request by agozhiy**
…me environments.

Added a check that prevents the cluster tear down if TestKafkaSuit is not running.

### CODE REVIEW

**Comment by arina-ielchiieva** [comment]
@aravi5 could you please take a look at this PR?

**Comment by vdiravka** [comment]
I have BUILD SUCCESS with this solution after `mvn test -pl contrib/storage-kafka` with 1, 2 and 3 number of `-DforkCount`.
I think the design of `TestKafkaSuit` could be improved to avoid such kind of issues. But with current design the solution looks good.
@aravi5 Do you agree?

**Comment by aravi5** [comment]
@agozhiy - Thank you for fixing this, the fix looks good.

@vdiravka  - The design of `TestKafkaSuit` is very similar to design of `MongoTestSuit` and hence would require changes similar to the ones made in [storage-mongo/pom.xml](https://github.com/apache/drill/pull/923/commits/f5dfa56f33a46b92e2f9de153d82a16a77642ddf#diff-e110e2cbfd77d27e85d5121529c612bfR83).

Current behavior is surefire runs tests classes twice - once as a part of `TestKafkaSuit` and the other by directly running classes. To prevent the latter from happening, changes were made in `pom.xml` for `storage-mongo` plugin. 

These changes can be addressed as a part of a separate PR or I am happy to include the changes as a part of my open PR https://github.com/apache/drill/pull/1463.

**Comment by vdiravka** [comment]
@aravi5 Sounds reasonable. Looks like your proposal fits DRILL-6625 and #1463 PR, so you can include it there.

**Comment by sohami** [comment]
Merged in master

**Pull request closed without merging**
