### PR TITLE
[DOC UPDATE] Grammar edit

### PR DESCRIPTION
**Pull request by fredster33**
# [DOC-UPDATE](https://issues.apache.org/jira/browse/DRILL-XXXX): Grammar Edit

(this is a small grammar edit for the README, so I didn't file a JIRA issue)

## Description
This PR fixed some grammar issues in the README.

## Documentation
This updated the README.

## Testing
None, this is a trivial change.

### CODE REVIEW

**Review by luocooong — COMMENTED** [review]
@fredster33 Hello. We just need to add `[DOC UPDATE]` in front of the title of the PR when update the docs. Thanks for your contribution.

**Comment by fredster33** [comment]
> @fredster33 Hello. We just need to add `[DOC UPDATE]` in front of the title of the PR when update the docs. Thanks for your contribution.

Edited!

**Review by dzamo — APPROVED** [review]

**Comment by dzamo** [comment]
@luocooong when the target branch is `gh-pages` I just go ahead and merge.  This commit is going to `master`, who should merge it?

**Comment by luocooong** [comment]
@dzamo Thanks for the review. cgivre can help with the merge. me too

**Pull request merged**
