### PR TITLE
DRILL-6970: fix issue with logregex format plugin where drillbuf was overflowing

### PR DESCRIPTION
**Pull request by jcmcote**
fix bug in string_binary, it was not doing reallocIfNeeded

### CODE REVIEW

**Comment by arina-ielchiieva** [comment]
@cgivre could you please review?

**Comment by arina-ielchiieva** [comment]
@jcmcote https://issues.apache.org/jira/browse/DRILL-7029 is different issue. Could you please add proper Jira number or file new Jira? Also please updated commit message.

**Comment by cgivre** [comment]
Here's a link which explains how to change the commit message:
https://stackoverflow.com/questions/8981194/changing-git-commit-message-after-push-given-that-no-one-pulled-from-remote

**Comment by arina-ielchiieva** [comment]
@cgivre looks like @jcmcote addressed all requested changes. Is the PR ready-to-commit? If yes, please add +1 and add ready-to-commit label in Jira.

**Comment by cgivre** [comment]
+1

**Pull request closed without merging**
