### PR TITLE
DRILL-6970: Issue with LogRegex format plugin where drillbuf was overflowing 

### PR DESCRIPTION
**Pull request by jcmcote**

### CODE REVIEW

**Comment by jcmcote** [comment]
I've added a testcase. It's ready for code review.

**Comment by vdiravka** [comment]
@jcmcote Thanks for PR. It is not ready for review yet. Please squash all commits into one and rebase your branch onto the latest Apache Drill master branch due to conflicts:
> This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch.

**Comment by sohami** [comment]
@jcmcote - Are you planning to re-open this PR ?

**Comment by jcmcote** [comment]
it looks like it was approved but not yet merged?

**Comment by arina-ielchiieva** [comment]
@jcmcote you have closed the PR before the merge, thus it still have not been merged. Can you please re-open it and squash the commits?

**Comment by arina-ielchiieva** [comment]
@jcmcote re-openned PR myself, you still need to resolve the conflicts and squash the commits.

**Comment by sohami** [comment]
@jcmcote @arina-ielchiieva - I don't see any review for this PR. How's it approved ?

**Comment by arina-ielchiieva** [comment]
@sohami my bad, I am not sure why I decided that PR has been reviewed.
@cgivre / @vdiravka could you please review?

**Comment by cgivre** [comment]
@vdiravka  I can do the review if you'd like.  There was a similar PR open and I asked for a unit test which was addressed.

**Comment by arina-ielchiieva** [comment]
@cgivre sure, please review.

**Comment by ihuzenko** [comment]
@jcmcote I'd like to suggest redesign the **LogRecordReader** a little bit. The main idea is to extract all try-catches from _**load(int rowIndex, String value)**_ methods of each concrete **ColumnDefn** implementation and make one unified ```try-cacth``` which will wrap whole loop used for reading and handling of each line in log file for the reader (the while loop inside ```next()```). Such approach will reduce boilerplate code and expected that it'll work faster, because try-catch will be initiated once per row batch instead of each column of each line (row). Note that it's not requirement for this pull request, but rather suggestion for future improvement.

**Comment by sohami** [comment]
@cgivre - Can you please review this PR ?

**Comment by cgivre** [comment]
Sorry.  Will review this weekend.

**Comment by cgivre** [comment]
I couldn't execute the code on my machine because the PR needs a rebase.  The code looks good however.  I would like to actually run the unit test.

**Comment by vvysotskyi** [comment]
Closing this PR, since the latest changes are present in https://github.com/apache/drill/pull/1673

**Pull request closed without merging**
