### PR TITLE
DRILL-6540: Upgrade to HADOOP-3.0 libraries

### PR DESCRIPTION
**Pull request by vdiravka**
- accommodate Apache and MapR profiles with Hadoop 3.0.3 library versions
- update HBase version
- fix jdbc-all Woodox dependency
- unban Apache commons-logging dependency

Draft PR until all regression tests pass, Drill will be tested in distributed mode on the 3.0 Hadoop cluster, all unwanted dependencies will be excluded from `jdbc-all` jar and the "Hadoop 3" topic will be discussed with a community.

### CODE REVIEW

**Comment by vvysotskyi** [comment]
@vdiravka, did you have a chance to check whether there wouldn't be problems on Windows with these changes since the version of `hadoop-winutils` is still 2.7.1?

**Comment by cgivre** [comment]
Is there any update on this PR?

**Comment by jhamit** [comment]
Thank you @vdiravka  ! To further encourage this work, these changes are required to support S3 v4 APIs which are now required in new AWS regions (see this link for up-to-date list: https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region). Additionally, v2 is currently scheduled to be completely deprecated by June 24, 2020 (https://aws.amazon.com/blogs/aws/amazon-s3-update-sigv2-deprecation-period-extended-modified/) . For these reasons, our team is already considering pulling this fix in manually.

**Comment by arina-ielchiieva** [comment]
@vvysotskyi since you were the reviewer do you recall what else should be done to finish this work?
cc @agozhiy @denysord88

**Comment by vvysotskyi** [comment]
Here is the list of things to be done before merging this PR:

- [ ] Cleanup poms:
- - [ ] Remove commented out lines, revise new dependencies to reduce JDBC driver size
- - [ ] Revert removing excluding `commons-logging`, it will be better to add an absent mock class from `commons-logging` to Drill
- [ ] Remove change with logging test error in `ITTestShadedJar.java`
- [ ] Test Drill on Hadoop 3 cluster (secure, non-secure modes)
- [ ] Test Drill in embedded mode on Windows (test Hadoop win-utils)
- [ ] Test JDBC client with new Hadoop version
- [ ] Check whether new Hadoop version API is compatible with the current one, in the case if not, decide whether to introduce new profile, use a property to specify the version during building or document supported versions

**Comment by cgivre** [comment]
@vvysotskyi 
Can anyone assist with these tasks, or are you actively working on them?  Do you think it would be possible to get this JIRA into Drill 1.17?

**Comment by arina-ielchiieva** [comment]
@agozhiy could you please assist?

**Comment by arina-ielchiieva** [comment]
Looks like there are some changes required plus through testing, @agozhiy and @denysord88 are going to work on this but most likely changes will be put in 1.18 release.

**Comment by arina-ielchiieva** [comment]
Closing in favor of https://github.com/apache/drill/pull/1895.

**Pull request closed without merging**
