### PR TITLE
DRILL-8095: upgrade to poi 5.2.0

### PR DESCRIPTION
**Pull request by pjfanning**
# [DRILL-8095](https://issues.apache.org/jira/browse/DRILL-8095): upgrade to poi 5.2.0

## Description

upgrade to poi 5.2.0

## Documentation
No changes

## Testing
existing unit tests

### CODE REVIEW

**Review by cgivre — APPROVED** [review]
LGTM +1 

@pjfanning, Thanks for this contribution!  I saw in the original JIRA, it mentions ignoring cell styles, but I didn't see that in this PR.  Did the new excel streaming reader take care of that?
(I'm fine with merging as is, but just curious)

**Comment by pjfanning** [comment]
@cgivre see latest comment on https://issues.apache.org/jira/browse/DRILL-8095 - not loading the styles breaks existing Drill tests - so I abandoned that bit of the change

**Comment by cgivre** [comment]
> @cgivre see latest comment on https://issues.apache.org/jira/browse/DRILL-8095 - not loading the styles breaks existing Drill tests - so I abandoned that bit of the change

Roger that.... Sorry I didn't see that.  We don't have to include it in this PR, but if you can recommend a better way of inferring the data type that would be more performant, I'm all ears.  I did it using the Cell style because that seemed to make the most sense.   Thanks!

**Comment by pjfanning** [comment]
tbh styles should used if you are inferring the schema - I just thought the existing code wasn't using them

One enhancement that I think Drill needs is to allow the format-excel code to process a number of rows (maybe defaulting to something like 5 or 10) when inferring the schema - this would help if the first data row has null values in some columns - or you might have a column that some times has numeric values but other times text and in that case the schema would need to make that cell text based.

**Comment by cgivre** [comment]
> tbh styles should used if you are inferring the schema - I just thought the existing code wasn't using them
> 
> One enhancement that I think Drill needs is to allow the format-excel code to process a number of rows (maybe defaulting to something like 5 or 10) when inferring the schema - this would help if the first data row has null values in some columns - or you might have a column that some times has numeric values but other times text and in that case the schema would need to make that cell text based.

I'd definitely agree with this approach.  I am actually working on a storage plugin for Google Sheets [1] which does exactly that.  There is a `typifier` class which reads the data from a column and attempts to infer the data type.  Perhaps once that gets merged, we can reuse the `typifier` for the Excel reader and use this approach. 


[1]: https://github.com/cgivre/drill/tree/storage-googlesheets/contrib/storage-googlesheets

**Pull request merged**
