### PR TITLE
DRILL-7868: Restore correct master branch state

### PR DESCRIPTION
**Pull request by vvysotskyi**
# [DRILL-7868](https://issues.apache.org/jira/browse/DRILL-7868): Restore correct master branch state

## Description
This PR reverts not approved changes for DRILL-7863 and adds changes reverted in the commit after that. 

## Documentation
NA

## Testing
Compared with version before two commits.

### CODE REVIEW

**Comment by cgivre** [comment]
LGTM +1

**Comment by vdiravka** [comment]
@vvysotskyi Could you add links to commits, which were reverted. It will be useful in git annotations usage

**Comment by vvysotskyi** [comment]
@vdiravka, good idea, added to the commit message (second line).

**Comment by cgivre** [comment]
@vvysotskyi Are we good to merge?

**Pull request merged**
