### PR TITLE
DRILL-7267: Add Slack Link in Documentation

### PR DESCRIPTION
**Pull request by coderfender**

### CODE REVIEW

**Comment by cgivre** [comment]
LGTM +1

**Comment by coderfender** [comment]
@cgivre , Is there anything else you want me to add to this or we can merge this to master ?

**Comment by cgivre** [comment]
One more thing... Can you please change the commit message to:
DRILL-7267: Add Slack Link in Documentation

**Comment by coderfender** [comment]
@cgivre ,

I changed the commit message as well. Thank you for strictly enforcing standards. I will keep this in mind for future PRs ( :) )

**Comment by vvysotskyi** [comment]
@cgivre, could you please resolve corresponding Jira ticket after the PR is merged?

**Comment by coderfender** [comment]
@vvysotskyi , I resolved the issue. Thank you

**Pull request merged**
