### PR TITLE
Add Github issue templates

### PR DESCRIPTION
**Pull request by cgivre**
Github offers automated feature request and bug report templates for repos.  This PR adds them to Drill.

### CODE REVIEW

**Comment by luocooong** [comment]
@cgivre Hi, Do we need to enable the GitHub `ISSUES` panel?

**Comment by cgivre** [comment]
> @cgivre Hi, Do we need to enable the GitHub `ISSUES` panel?

Good point.  Personally I think that's a good idea as well.  When people actually start working on things we can use JIRA to track work. (Or get rid of JIRA entirely).

**Comment by luocooong** [comment]
Great start. I think JIRA can be the wiki of Drill project (The past, present and future of Drill), then issues panel of Github is the  milestone and "Idea Pool". What do you think, @cgivre @dzamo @vvysotskyi @vdiravka ?

**Comment by luocooong** [comment]
There is one more thing. I think that after 1.19, we don’t need to collect too many changes to release new version. Can we release a version using  a fixed time, such as every quarter?

**Comment by cgivre** [comment]
> There is one more thing. I think that after 1.19, we don’t need to collect too many changes to release new version. Can we release a version using a fixed time, such as every quarter?

I personally am very much in favor of more frequent releases.   We could do the `tick tock` releases where by every quarter we do a release.  Even number releases are more "major" and odd releases are "minor".  I think that was how Cassandra did it for a number of years.  I just hate the idea that people are using Drill 1.18 when we've fixed so many bugs and made so many performance improvements.

**Comment by dzamo** [comment]
> Great start. I think JIRA can be the wiki of Drill project (The past, present and future of Drill), then issues panel of Github is the milestone and "Idea Pool". What do you think, @cgivre @dzamo @vvysotskyi @vdiravka ?

I think putting a wiki in Jira would be a bit of a square peg in a round hole.  Atlassian makes something called Confluence for wikis which I've never tried, but in my opinion Paul Rogers' wiki shows that Github provides a reasonable option for hosting wikis.  That, with the issue templates at the top of this thread, could make Github even more of a one-stop shop for us.

**Comment by luocooong** [comment]
@cgivre Full support to that proposal.
@dzamo Let me explain that I hope to protect the integrity of JIRA. In fact, I will also prefer  to use the Wiki of GitHub for technical documentation.

**Review by luocooong — APPROVED** [review]
@cgivre Thanks for the PR. +1

**Comment by cgivre** [comment]
> > Great start. I think JIRA can be the wiki of Drill project (The past, present and future of Drill), then issues panel of Github is the milestone and "Idea Pool". What do you think, @cgivre @dzamo @vvysotskyi @vdiravka ?
> 
> I think putting a wiki in Jira would be a bit of a square peg in a round hole. Atlassian makes something called Confluence for wikis which I've never tried, but in my opinion Paul Rogers' wiki shows that Github provides a reasonable option for hosting wikis. That, with the issue templates at the top of this thread, could make Github even more of a one-stop shop for us.

@dzamo I am looking into activating wikis and issues for Drill's github repo.  Please standby.  In the meantime, I'll merge this.

**Pull request merged**
