### PR TITLE
DRILL-6785: DataClient is using RootAllocator in the bootstrap instea…

### PR DESCRIPTION
**Pull request by sohami**
…d of dataPool

### CODE REVIEW

**Comment by arina-ielchiieva** [comment]
@sohami the change seems obvious but could you please highlight what incorrect usage causes and how issue was found?

**Comment by sohami** [comment]
@arina-ielchiieva - There was no issues which was caused/found because of this. I happen to notice it while browsing code so made the change for correctness.

**Comment by arina-ielchiieva** [comment]
Sounds good, +1

**Comment by kkhatua** [comment]
@sohami what is teh QA impact for this?

**Pull request closed without merging**
