### PR TITLE
DRILL-7834: Add Utility Functions for Compressed Files

### PR DESCRIPTION
**Pull request by cgivre**
# [DRILL-7834](https://issues.apache.org/jira/browse/DRILL-7834): Add Utility Functions for Compressed Files

## Description

Some format plugins that use third party parsers throw errors when they receive compressed input streams from Drill.  This PR proposes to introduce three utility functions to the DrillFileSystem:
* `isCompressed(<path>)`:  Returns true/false whether the input file is compressed
* `getCodec(<path>)`  This method returns the codec of the file if any
* `openDecompressedInputStream(<path>)`:  Returns an InputStream that should be readable by parsers that read raw bytes.  This method converts the original InputStream to a byte[] first, then returns that via a ByteArrayInputStream.

## Documentation
No user facing changes.

## Testing
Tested manually.

### CODE REVIEW

**Review by luocooong — APPROVED** [review]
@cgivre  The `To EVF` work needs these good ideas. Is it possible to add a comment for `openPossiblyCompressedStream()` function to describe the differences of them?

**Comment by cgivre** [comment]
> @cgivre The `To EVF` work needs these good ideas. Is it possible to add a comment for `openPossiblyCompressedStream()` function to describe the differences of them?

@luocooong 
Thanks for the review.   The `openPossiblyCompressedStream()` function opens an InputStream but if the file is compressed you can get a ZipCompressedStream or something like that.  In most cases, it won't matter, however, I found that in the case of a proprietary plugin that I was working on which read a byte array.  I'm not sure exactly why, but the Zip stream was breaking the reader.   The plugin in question also didn't work on S3 for the same reason.   

I'm working on refactoring the LTSV plugin and was running into the same issue.   Hopefully this will make future development a little easier.

**Comment by cgivre** [comment]
I can add a comment.  If you're approving this PR, could you please add a `+1` to the comment?

**Comment by luocooong** [comment]
+1

**Comment by cgivre** [comment]
@luocooong 
I added a comment explaining the methods.

**Pull request merged**
