### PR TITLE
DRILL-7814: Add Limit Pushdown to MongoDB Storage Plugin

### PR DESCRIPTION
**Pull request by cgivre**
# [DRILL-7814](https://issues.apache.org/jira/browse/DRILL-7814): Add Limit Pushdown to MongoDB Storage Plugin

## Description
This PR adds a limit pushdown capability to the MongoDB storage plugin. 

## Documentation
No user visible changes

## Testing
Added new class of unit tests for the pushdown.

### CODE REVIEW

**Review by vvysotskyi — APPROVED** [review]
+1

**Comment by cgivre** [comment]
@vvysotskyi 
Thanks for the review!  I was messing with this a bit more and found that it doesn't seem to push down the limit when there are filters in the query.  Should we address that in future work and commit this as is?

**Comment by vvysotskyi** [comment]
@cgivre, thanks for pointing to this issue, I think it is better to address it in the scope of this PR.

**Comment by cgivre** [comment]
> @cgivre, thanks for pointing to this issue, I think it is better to address it in the scope of this PR.

Could you give me any suggestions on this?  It didn't seem like `scanStats` were doing anything with the filters.  Do you think reworking this method would fix this?  I was trying to keep this change as small as possible.

**Comment by vvysotskyi** [comment]
@cgivre, looks like I've found the reason why the limit cannot be applied for the case you have pointed.
Drill uses the `DrillPushLimitToScanRule` rule to push the limit to scan. This rule can be applied at the **logical** planning phase.
Mongo storage plugin uses the `MongoPushDownFilterForScan` rule to push filter to scan. This rule is applied at the **physical** planning phase (in its constructor it passes `FilterPrel`and `ScanPrel` rel nodes to match).

The solution for this issue is quite simple - update `MongoPushDownFilterForScan` to be able to work apply at any phase, for it, please replace  `FilterPrel` with `org.apache.calcite.rel.core.Filter` and `ScanPrel` with `DrillScanRelBase`.

**Comment by cgivre** [comment]
> @cgivre, looks like I've found the reason why the limit cannot be applied for the case you have pointed.
> Drill uses the `DrillPushLimitToScanRule` rule to push the limit to scan. This rule can be applied at the **logical** planning phase.
> Mongo storage plugin uses the `MongoPushDownFilterForScan` rule to push filter to scan. This rule is applied at the **physical** planning phase (in its constructor it passes `FilterPrel`and `ScanPrel` rel nodes to match).
> 
> The solution for this issue is quite simple - update `MongoPushDownFilterForScan` to be able to work apply at any phase, for it, please replace `FilterPrel` with `org.apache.calcite.rel.core.Filter` and `ScanPrel` with `DrillScanRelBase`.

Hey @vvysotskyi, I tried doing this in the `MongoPushDownFilterForScan` and either I missed something, but I'm getting all kinds of errors when I did this.  Could you take a quick look?

Thanks!

**Comment by vvysotskyi** [comment]
@cgivre, there are some additional follow-up changes that should be made. In `matches()` method and in the first line of `onMatch()` please replace `DrillScanRel` with `DrillScanRelBase`. When creating `newScanPrel`, it should be either `ScanPrel` or `DrillScanRel`, depending on the type of `scan`.

**Comment by cgivre** [comment]
> @cgivre, there are some additional follow-up changes that should be made. In `matches()` method and in the first line of `onMatch()` please replace `DrillScanRel` with `DrillScanRelBase`. When creating `newScanPrel`, it should be either `ScanPrel` or `DrillScanRel`, depending on the type of `scan`.

@vvysotskyi 
Thanks for the response.  I made a few changes but am stuck again.  It would seem that I need to check the query phase, but I'm not quite sure how to do that.  This is the error I'm getting now. 

```
org.apache.drill.exec.rpc.RpcException: org.apache.drill.common.exceptions.UserRemoteException: SYSTEM ERROR: AssertionError: Relational expression ScanPrel#133 has calling-convention LOGICAL but does not implement the required interface 'interface org.apache.drill.exec.planner.logical.DrillRel' of that convention
```

**Comment by vvysotskyi** [comment]
@cgivre, the failure should be fixed by addressing the comment above:
> When creating newScanPrel, it should be either ScanPrel or DrillScanRel, depending on the type of scan.

It may be done by adding a copy method that accepts group scan to `DrillScanRelBase`, implementing it in both inheritors, and using this method in the rule instead of explicitly creating `ScanPrel`.

**Review by vvysotskyi — APPROVED** [review]
LGTM, +1 🙂

**Pull request merged**
