### PR TITLE
DRILL-7997: Fix the type mismatch of mongo module in eclipse

### PR DESCRIPTION
**Pull request by luocooong**
# [DRILL-7997](https://issues.apache.org/jira/browse/DRILL-7997): Fix the type mismatch of mongo module in eclipse

## Description

Import the source code into the Eclipse (newer version), got the error message below :
```
Type mismatch: cannot convert from Z#0-SELF'#8 extends GenericContainer<Z#0-SELF'#8> & ... to Z#0-SELF'#4 extends GenericContainer<Z#0-SELF'#4> & ...
```

image

## Documentation
N/A

## Testing
This error is gone in eclipse.

### CODE REVIEW

**Comment by cgivre** [comment]
@luocooong 
I'm not an Eclipse user.  I use Intellij, so I'm not the most qualified to review, but superficially it looks good.

**Comment by luocooong** [comment]
@cgivre Thanks for the comments. Actually, It's a issue related to the Eclipse (The same at the Mac, Ubuntu and Windows 10). But, we can also refactor the few code to reduce confusion for the contributor. In this case, the logic of the code has not changed.

**Review by cgivre — APPROVED** [review]
LGTM +1

**Comment by cgivre** [comment]
@luocooong Looks good.  Before we merge, can you rebase with the CI fixes and make sure everything passes?  Thx!!

**Comment by luocooong** [comment]
@cgivre Okay, I will do this tomorrow.

**Pull request merged**
