### PR TITLE
DRILL-6409: Updates mongo-java-driver to 3.8.0

### PR DESCRIPTION
**Pull request by pkfoury**
This driver solves an issue with displaying BigDecimal data from MongoDB.

### CODE REVIEW

**Comment by Ben-Zvi** [comment]
A Drill pull-request must correspond to a Jira case (e.g. DRILL-1234) explaining the problem being addressed.

**Comment by binodsarkar** [comment]
This is not working with mongodb 4.x

**Comment by arina-ielchiieva** [comment]
@binodsarkar please file Apache Jira.

**Comment by arina-ielchiieva** [comment]
Thanks.

**Pull request closed without merging**
