### PR TITLE
DRILL-3983: Small test improvements

### PR DESCRIPTION
**Pull request by julienledem**
improve error message when SQL parsing error
add a simple test to Parquet writer
make errors verbose by default in tests

### CODE REVIEW

**Comment by adeneche** [comment]
I would go against making errors verbose by default, unit tests are already printing tons of text and we have many negative tests that are expected to throw exceptions. If we enable verbose, those tests would print even more stuff.

**Comment by julienledem** [comment]
@adeneche I'm all for removing verbose logging. In this case, it sounds like we should go after bad logging rather than removing information from errors. 
Having "verbose errors" will actually enable less logging:
Currently the server side (drillbit) stack trace is lost when the exception goes through the RPC layer. Which means we rely on logging those errors on the server side to find the original stack trace.
the "verbose errors" setting will add the stacktrace in the exception message so that we get both the client and server side stacktrace from the client side exception. which would allow removing the server side logging in tests.

I think we should follow this general principle: If an exception is dealt with it should not be logged. Only exception that can not be dealt with should be logged as errors or warning depending on the effect.
A negative test would catch an exception and verify it. If logging happens at some layer bellow it, this sounds like it should be refactored.

**Comment by adeneche** [comment]
I'm not talking about logging. Most Drill unit tests rely on PrintResultsListener that will print the query's output to the standard output or a SilentListener that won't print the results but still prints the exception's message to the standard output.
Even if you catch the exception in the unit test, the exception message is still printed to the standard output.

**Comment by julienledem** [comment]
@adeneche Would you agree that changing those tests so that they don't print to standard output is the way to go? A test should print something only if the test is failing or logs are configured to show debug information.

**Comment by adeneche** [comment]
definitely. Actually I opened [DRILL-2950](https://issues.apache.org/jira/browse/DRILL-2950) just for that, but never got the time to work on it.

**Comment by julienledem** [comment]
@adeneche So, to your original comment. My point is your suggestion in DRILL-2950 is the way to go and that the (possibly misleadingly named) "verbose errors" option is actually a good thing in tests as it provides the original stacktrace without requiring extra logging. Do you agree?

**Comment by adeneche** [comment]
I agree. Once unit tests are no longer printing their output and their expected exceptions, having more details when a test fails, using "verbose errors", can definitely help

**Comment by jacques-n** [comment]
The verbose errors are super useful for debugging a failed test run. This is especially true in the context of a sporadic failure. I actually feel foolish for not having done this sooner. I don't think we should hold up this patch because too many tests are noisy. If that is important to someone, we should fix those. If merging this causes us to fix those sooner, then all the better.

**Comment by jaltekruse** [comment]
+1 to the change. I agree that we should be working to get this cleaned up sooner rather than later and this helps in the meantime with debugging.

**Comment by julienledem** [comment]
@adeneche Please see last commit. I made the output printing configurable so that it is less verbose in tests. https://github.com/apache/drill/commit/9b40f93122eb22055e9ebec287e5a5ebfa65a2fe

**Comment by adeneche** [comment]
that's definitely a step in the right direction.

**Comment by jacques-n** [comment]
lgtm. +1. Will merge shortly.

**Comment by jacques-n** [comment]
For reference, final tally shows that full test output went from 5.9M to 2.4M with this change. Nice improvement.

**Comment by julienledem** [comment]
Thanks!

**Pull request closed without merging**
