### PR TITLE
Improve MAVEN build Performance

### PR DESCRIPTION
**Pull request by ChenZhangg**
[Parallel builds in Maven 3](https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3) Maven 3.x has the capability to perform parallel builds.

=====================
If there are any inappropriate modifications in this PR, please give me a reply and I will change them.

### CODE REVIEW

**Comment by vdiravka** [comment]
@ChenZhangg we have already use parallel builds. And this 2 forks right now:
https://github.com/apache/drill/blob/master/pom.xml#L52
On the other hand, this is the issue, that some test fails intermittently right now for parallel maven builds. I am going to solve it in scope of: https://github.com/apache/drill/pull/2293


About `-T 1C`, it means to use the same number of forks as the number of cores on machine. But it also means we will use the same number of JVMs and the memory usage will be increased. Since Drill is memory cost tool and not all machines has enough amount of memory this option is not sufficient for all machines. For instance: user can have laptop with two physical cores, but with Intel multi-threading that number will be 4. The default memory usage for Drill in scope of one JVM is up to 4Gb. So for laptops with 8Gb memory the build will fail.

**Comment by cgivre** [comment]
> @ChenZhangg we have already use parallel builds. And this 2 forks right now:
> https://github.com/apache/drill/blob/master/pom.xml#L52
> On the other hand, this is the issue, that some test fails intermittently right now for parallel maven builds. I am going to solve it in scope of: #2293
> 
> About `-T 1C`, it means to use the same number of forks as the number of cores on machine. But it also means we will use the same number of JVMs and the memory usage will be increased. Since Drill is memory cost tool and not all machines has enough amount of memory this option is not sufficient for all machines. For instance: user can have laptop with two physical cores, but with Intel multi-threading that number will be 4. The default memory usage for Drill in scope of one JVM is up to 4Gb. So for laptops with 8Gb memory the build will fail.

@vdiravka Is that a -1 for this PR?  Should we close?

**Comment by vdiravka** [comment]
I waited the response from @ChenZhangg
@ChenZhangg any update?

As a default option `1C` might be not sufficient, because it can lead to failed maven build. But we might want to consider to add info in README about this option to speed up the Maven build on the powerful enough machines.

**Comment by cgivre** [comment]
> I waited the response from @ChenZhangg
> @ChenZhangg any update?
> 
> As a default option `1C` might be not sufficient, because it can lead to failed maven build. But we might want to consider to add info in README about this option to speed up the Maven build on the powerful enough machines.

@vdiravka In the docs[1] there are build quickly instructions:

```
mvn install -T 4 -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true -Dlicense.skip=true -Dcheckstyle.skip=true -Dfindbugs.skip=true -Dmaven.site.skip=true -Denforcer.skip=true -DskipIfEmpty=true -Dmaven.compiler.optimize=true
```

On my laptop, this command takes ~2 min whereas a regular build without the tests takes between 5-6.   Unless I hear otherwise, I'd suggest closing this PR.

[1]: https://github.com/apache/drill/blob/master/docs/dev/Environment.md

**Comment by cgivre** [comment]
@ChenZhangg 
Since we've not heard from you since posting the PR, I'm going to close this PR.  Feel free to reopen if you would like to continue the discussion.

**Pull request closed without merging**
