### PR TITLE
DRILL-6318

### PR DESCRIPTION
**Pull request by oleg-zinovev**
Test for DRILL-6099 was changed due it's incorrect behavior

### CODE REVIEW

**Comment by priteshm** [comment]
@ppadma can you review this?

**Comment by priteshm** [comment]
@arina-ielchiieva or @vdiravka  can you review this?

**Comment by amansinha100** [comment]
@oleg-zinovev good catch with the empty array input for Flatten.   I had reviewed the original JIRA DRILL-6099 but did not consider the empty arrays.  It would be good for @gparai to also take a look at this fix.

**Comment by oleg-zinovev** [comment]
Reason for build error: "The job is the maximum time limit for jobs, and has been terminated."
What should I do next?

**Comment by kkhatua** [comment]
You could try re-pushing the last commit with a different commit ID (change a trailing text in the PR to have Git generate a different ID). I don't see an option within Travis to resubmit.

**Comment by arina-ielchiieva** [comment]
@oleg-zinovev could you please rebase to the latest master?

**Comment by oleg-zinovev** [comment]
Rebased

**Pull request closed without merging**
