### PR TITLE
DRILL-6195: Quering Hive non-partitioned transactional tables via Drill

### PR DESCRIPTION
**Pull request by vdiravka**

### CODE REVIEW

**Comment by vdiravka** [comment]
@arina-ielchiieva Please review

**Comment by arina-ielchiieva** [comment]
Looks good, could you add unit test?

**Comment by vdiravka** [comment]
@arina-ielchiieva Current implementation of creating schema for Drill Hive embedded metastore doesn't allow to create transactional tables. That's why I have created a separate Jira task to update Drill HiveTestGenerator - [DRILL-6196](https://issues.apache.org/jira/browse/DRILL-6196).

**Comment by arina-ielchiieva** [comment]
+1

**Pull request closed without merging**
