### PR TITLE
DRILL-6190 - Fix handling of packets longer than legally allowed.

### PR DESCRIPTION
**Pull request by tdunning**

### CODE REVIEW

**Comment by priteshm** [comment]
@parthchandra or @arina-ielchiieva  can you review this?

**Comment by parthchandra** [comment]
+1

**Comment by arina-ielchiieva** [comment]
@tdunning travis fails with `
Failed tests: 
  TestPcapRecordReader.testDistinctQuery:51->runSQLVerifyCount:56->printResultAndVerifyRowCount:68 expected:<1> but was:<2>`

**Comment by tdunning** [comment]
Fixed the test regression. Deferring investigation into why the data field doesn't look unique to Drill because we will probably need to revamp how raw data is returned anyway.

**Pull request closed without merging**
