### PR TITLE
DRILL-8044: remove Strings.java and add dependency on log4j-api instead

### PR DESCRIPTION
**Pull request by pjfanning**
# [DRILL-8044](https://issues.apache.org/jira/browse/DRILL-8044): remove Strings.java and add dependency on log4j-api instead

Remove copy of log4j2 Strings.java and add explicit dependency on log4j-api jar

## Description

This Strings.java causes issues when log4j2 is used. https://issues.apache.org/jira/browse/HIVE-23088 is the bug that leads to all this mess - no release of Hive has been made with this Hive fix.

## Documentation

Shouldn't require doc change

## Testing

unit tests

### CODE REVIEW

**Review by vvysotskyi — CHANGES_REQUESTED** [review]
-1 for this change, we shouldn't have a dependency on `log4j` since we already use `slf4j` logging in the project, and using multiple logger dependencies will cause issues with resolving the actual logger.

**Comment by pjfanning** [comment]
@vvysotskyi @cgivre this change is due to a bug in Hive that has a dependency on log4j-api jar - log4j-api is only part of log4j - not the full log4j solution

**Comment by vvysotskyi** [comment]
@pjfanning, even having `log4j-api` might conflict with `log4j-over-slf4j`, so it shouldn't be added.
`Strings.java` was introduced as a workaround, but the actual issue is that Hive has a direct dependency in the code on `log4j-api`, but it shouldn't. 

If there are other libraries that also do that, we can update `Strings.java` with the required changes to resolve run-time errors and create tickets for those libraries to remove such code, so eventually, this workaround will be removed.

**Comment by pjfanning** [comment]
@vvysotskyi I added https://github.com/apache/drill/pull/2375 as an alternate.

**Pull request closed without merging**
