### PR TITLE
[DOC UPDATE] Drill provider for Airflow blog post.

### PR DESCRIPTION
**Pull request by dzamo**
# [DOC UPDATE] Drill provider for Airflow blog post.

## Description

This is is the fluffy, story telling, motivational piece for the Drill provider in Airflow (ignore the other random doc page rewording of "clobber" that slipped into the PR).  

I started on a tutorial but found myself explaining "when and why might we do this?" for a good few paragraphs so I embraced that and moved the content over to this blog post.  I'll go back to a simple tutorial page next.  All suggestions welcome.

### CODE REVIEW

**Review by cgivre — COMMENTED** [review]
@dzamo 
Thanks for this!  
While I'm fine with committing this now, do you really want to merge this with the last sentence that says more coming soon, or just wait until you have that written?

**Comment by luocooong** [comment]
@dzamo Would you mind me posting your blogs to Chinese channel?

**Comment by dzamo** [comment]
It can totally wait to be merged when the tutorial is written.  I get 
pretty busy from tomorrow until Thursday but it's not like this PR 
patches a CVE or something :-).

Btw, thinking as I wrote that post inspired some thoughts about the 
pre-ETL data exploration phase that analysts go through, and what Drill 
could help with.  Like a function to produce value histograms (Unicode 
art or SVG) straight from a query over e.g. JSON.  Or a function for 
data type profiling (returns # valid 32-bit integers, # valid floats, etc.)

**Comment by dzamo** [comment]
I would be honoured :-)

**Review by paul-rogers — APPROVED** [review]
Very nice. +1

**Comment by dzamo** [comment]
Closing because these doc commits have been pushed directly to gh-pages.

**Pull request closed without merging**
