### PR TITLE
DRILL-4525: Allow SqlBetweenOperator to accept LOWER_OPERAND and UPPE…

### PR DESCRIPTION
**Pull request by hsuanyi**
…R_OPERAND with different types

### CODE REVIEW

**Comment by hsuanyi** [comment]
@jinfengni  can you help review? Thanks.

**Comment by jacques-n** [comment]
Did you propose this change in the Calcite community and get rejected? Also, can't we return multiple SqlBetweenOperators, including both the Calcite one and one that matches the Drill spec?

**Comment by jinfengni** [comment]
Looks like the root cause of the problem is Calcite does not allow the comparison of Date and Timestamp.

{code}
select CAST('1990-01-01' AS DATE) < CAST('2001-01-01' AS TIMESTAMP) FROM (VALUES(1, 2)) AS T(A,B);
Mar 24, 2016 8:15:53 AM org.apache.calcite.sql.validate.SqlValidatorException <init>
SEVERE: org.apache.calcite.sql.validate.SqlValidatorException: Cannot apply '<' to arguments of type '<DATE> < <TIMESTAMP(0)>'. Supported form(s): '<COMPARABLE_TYPE> < <COMPARABLE_TYPE>'
{code}

Postgres, on the country, supports date vs timestamp compare, through implicit cast.

{code}
select CAST('1990-01-01' AS DATE) < CAST('2001-01-01' AS TIMESTAMP) FROM (VALUES(1, 2)) AS T(A,B);
 ?column?
----------
 t
(1 row)
{code}

I looked through SQL standard, and could not find the rules for the implicit cast, which means different system could choose it's own interpretation.  (In other words, it's hard to argue what Calcite is doing is not right)

What Sean is trying to do with his proposal is to replace Calcite's between operator with Drill's between operator, so that the checkOperand will use Drill's rule.

**Comment by jacques-n** [comment]
I'm confused by a couple things. One, it sounds there is an issue with the convertlet that Sean is trying to manage. Can't we just make are own convertlets? Second, if the issue is this comparison of types, shouldn't we just add another operator that supports that. It seems like this wrapper situation will get ugly quickly if we don't find a better way to merge our operators with Calcite's.

**Comment by jinfengni** [comment]
My understanding is adding another operator will not work, since Calcite parser has put the built-in between operator in the sql expression tree[1]. The validator logic will simply use the build-in operator, even we add another operator. 

[1] https://github.com/apache/calcite/blob/master/core/src/main/codegen/templates/Parser.jj#L2564

**Comment by jacques-n** [comment]
Got it. We should open a discussion on this on the Calcite list. We shouldn't have to jump through hoops to change the implementation. Maybe the overridden operator table should be available in the parsing context. Or?

**Comment by hsuanyi** [comment]
In addition to @jinfengni's point:
@sudheeshkatkam did a proposal to add a new SqlAvgAggFunction (the inference mechanism of the original is not ideal for Drill). It was declined by Calcite's community, and the argument was adding unnecessary duplicates to the code. I think this argument is fair. Otherwise, there might be tens of variants for a single operator.

Regarding adding a new converlet:
Initially, I though having three wrappers (operator, function, agg function) are sufficient for all scenarios. However, at one method during conversion, the type SqlBetweenOperator is being expected. Thus, I decided to add a new wrapper which extends SqlBetweenOperator, so we do not need to do anything in conversion.

Certainly, we might be able to attain by not adding a new wrapper but adding a new converlet. I would not prefer this approach since 
1. I tried not to spread out the code complexity (introduced by inference and operand type check) to too many places. 
2. Adding our own converlet also introduces code complexity. And it probably is more complicated than a wrapper.

**Comment by julianhyde** [comment]
Calcite allows strings to be implicitly converted to DATE and TIMESTAMP values in comparisons, as does the SQL standard. Even if, as @jinfengni says, the standard does not allow implicit conversion when comparing a DATE and TIMESTAMP, it still seems a reasonable thing to do.

**Comment by hsuanyi** [comment]
merge this PR with https://github.com/apache/drill/pull/489. So close this one.

**Pull request closed without merging**
