### PR TITLE
DRILL-7994: Bump T-Digest to Latest Version

### PR DESCRIPTION
**Pull request by cgivre**
# [DRILL-7994](https://issues.apache.org/jira/browse/DRILL-7994): Bump T-Digest to Latest Version

## Description
Bump T-Digest to latest version.

## Documentation
N/A

## Testing
Ran unit tests

### CODE REVIEW

**Comment by cgivre** [comment]
@tdunning Care to review?

**Comment by cgivre** [comment]
> @tdunning Care to review?

Hold on... there's a test failure I need to investigate.

**Comment by tdunning** [comment]
Happy to review at some point that you think is appropriate.

Test failures can be regression tests that aren't really functional issues.

**Comment by jnturton** [comment]
Hi @cgivre, did you track down the test failure?  Want any help here?

**Comment by cgivre** [comment]
@jnturton I thought this would be a simple update, then the test broke. :-(   I probably won't have time to dig into this any time soon, so if you want to take a look, please feel free.

**Comment by tdunning** [comment]
The logs aren't visible right now so it is very hard to tell what's up.

**Comment by jnturton** [comment]
@cgivre can you trigger another CI run here? Doesn't look like I can.

**Comment by jnturton** [comment]
I've picked this and some other dependency updates up in #2432.  Closing this in favour of that.

**Pull request closed without merging**
