### PR TITLE
DRILL-8044: Update contrib/storage-hive copy of log4j Strings.java

### PR DESCRIPTION
**Pull request by pjfanning**
# [DRILL-8044](https://issues.apache.org/jira/browse/DRILL-8044): Update contrib/storage-hive copy of log4j Strings.java

Relates to pjfanning/excel-streaming-reader#76. This is an alternate to https://github.com/apache/drill/pull/2374.

## Description

https://github.com/apache/drill/blob/master/contrib/storage-hive/core/src/main/java/org/apache/logging/log4j/util/Strings.java is a copy of the real Log4j class but causes issues for Apache POI Excel code that relies on the latest Log4j code.)

## Documentation
Shouldn't require doc change

## Testing
unit tests

### CODE REVIEW

**Comment by pjfanning** [comment]
@vvysotskyi one of the travis-ci runs failed due a forked jvm running tests crashing - this happened before the module with the change was reached - is there anyway to get the tests rerun?

**Comment by vvysotskyi** [comment]
@pjfanning, since this change is required for updating poi and excel-streaming-reader, could you please update them here and ensure that the issue is resolved?

(Version update was reverted in this commit: https://github.com/apache/drill/commit/56ff6556b83ca0c3364592ade73d9e7436fcab44)

Also, please include the Apache Jira ticket into the commit message and update references in this PR.

**Comment by vvysotskyi** [comment]
I'll restart Travis CI tests now

**Comment by pjfanning** [comment]
@cgivre You reported the initial issue - would you be able to try this out with a POI 5.1.0 (and excel-streaming-reader 3.2.3)?

**Comment by cgivre** [comment]
@pjfanning 
Sure thing!  I'll build and report back this evening.  (I'm on ET in the US)

**Comment by cgivre** [comment]
@vvysotskyi Will we know if this prevents Hive queries from functioning?

**Comment by vvysotskyi** [comment]
@cgivre, hive unit tests would catch such issues, changes in this PR doesn't look to break the Hive

**Comment by cgivre** [comment]
@vvysotskyi 
The reason I'm asking is that the Excel unit tests all worked for the Excel plugin, but it wasn't until I manually ran a query, things broke.  I don't have a Hive installation to manually test.

**Comment by vvysotskyi** [comment]
@cgivre, it means that excell tests should be improved to use that code path, also there might be some additional dependencies for a test scope, so tests path, but actually it didn't work.

No need to check Hive, it wouldn't be broken with these changes

**Comment by vvysotskyi** [comment]
@pjfanning, looks like POI has a hard dependency on log4j. Could you please add a dependency on `log4j-to-slf4j` to `pom.xml` to allow using that library?

**Comment by pjfanning** [comment]
@vvysotskyi made the log4j dependency change but the CI/CD build timed out when trying to get the pom - seems like an env issue at time of build

**Comment by cgivre** [comment]
> @vvysotskyi made the log4j dependency change but the CI/CD build timed out when trying to get the pom - seems like an env issue at time of build

There's a major google issue happening right now.   I'll restart the CI once everything finishes.  It looks like everything is passing.

**Review by cgivre — APPROVED** [review]
LGTM +1

@pjfanning Thank you for contributing this.  I ran locally and it successfully queried Excel files.

**Comment by cgivre** [comment]
@pjfanning @vvysotskyi 
Thank you for all your work on this.  I restarted the CI, and assuming it passes this time, I'll merge later today.

**Review by vvysotskyi — APPROVED** [review]
+1, thanks for making changes.

**Pull request merged**
