### PR TITLE
Add doc: Using Saiku Analytics with Apache Drill

### PR DESCRIPTION
**Pull request by brenopolanski**

### CODE REVIEW

**Comment by kkhatua** [comment]
@bbevens  could you review this?

**Comment by brenopolanski** [comment]
Any news @kkhatua and @bbevens ?

**Comment by brenopolanski** [comment]
Okay.. thks @bbevens

**Comment by arina-ielchiieva** [comment]
@bbevens what the status of the doc? Can we close the PR?

**Comment by bbevens** [comment]
Hi @brenopolanski, I created an Ecosystem section where we will add community and commercial offerings based on Apache Drill. I created a placeholder for your content here: http://drill.apache.org/docs/using-saiku-analytics-with-apache-drill/ 
Can you please change the pull request to this location?

**Comment by brenopolanski** [comment]
Hey @bbevens ... i moved to right location :)

**Pull request merged**
