### PR TITLE
DRILL-7790 : Build Drill with Netty version 4.1.50.Final

### PR DESCRIPTION
**Pull request by alkakumari42**
[DRILL-7790](https://issues.apache.org/jira/browse/DRILL-7790): Build Drill with Netty version 4.1.50.Final

Updated Netty version to 4.1.50.Final and have modified the code accordingly 

## Documentation
(Please describe user-visible changes similar to what should appear in the Drill documentation.)

## Testing
(Please describe how this PR has been tested.)

### CODE REVIEW

**Comment by cgivre** [comment]
@alkakumari42 
Can you please take a look at the merge conflict?
Thanks!

**Comment by alkakumari42** [comment]
> @alkakumari42
> Can you please take a look at the merge conflict?
> Thanks!

Hi, 

Resolved the conflicts.

Thanks,
Alka

**Comment by cgivre** [comment]
@alkakumari42 
There are still branch conflicts.  Can you please take a look?
Thanks!

**Comment by alkakumari42** [comment]
> @alkakumari42
> There are still branch conflicts. Can you please take a look?
> Thanks!

Hi @cgivre ,

Please note that the changelist I have added is currently not with the intent of merging, but rather as a frame of reference. The actual issue is that the up-gradation which I tried did not seem to work, so was wondering if someone from the open-source community could provide some assistance by looking at the changelist, or, just generally suggesting what needs to be done in order to upgrade netty, since the one being used contains vulnerabilities.

Regards,
Alka

**Comment by alkakumari42** [comment]
Hi @cgivre, 

Did you get a chance to look into this issue?
Kindly, let me know if you find something wrong with my changelist or if there are some other changes needed as well. 

Regards,
Alka

**Comment by cgivre** [comment]
> Hi @cgivre,
> 
> Did you get a chance to look into this issue?
> Kindly, let me know if you find something wrong with my changelist or if there are some other changes needed as well.
> 
> Regards,
> Alka

@alkakumari42 
Thank you for the contribution.  We're happy to commit this, but we can't merge this until the conflicts are resolved.  Can you please rebase this PR on the current master, and fix any merge conflicts?  Finally, we'll need you to squash all commits.  If you need help with this, let me know. 

Thanks and Happy Holidays!

**Comment by alkakumari42** [comment]
Hi @cgivre,

Actually, the changes that I have made is not with the intent of merging to the codebase. It's more of a demonstration of Netty jar up-gradation. As we tried to upgrade the Netty jar, we found there are many breaking changes that have been introduced. 
So, the issue is not to resolve the conflict and merge the code. It's about how can we upgrade some jars that are being used in opensource code.
We have tried to upgrade from our end and modify the code accordingly. But, it didn't seem to work. If there is some suggestion on how to upgrade some of the jars used by open-source code or should we wait for the Netty jar up-gradation by the open-source community?

Regards,
Alka

**Comment by cgivre** [comment]
This has been resolved in https://github.com/apache/drill/pull/2185.  Closing PR.

**Pull request closed without merging**
