### PR TITLE
Fix formatting on "MongoDB Storage Plugin" page

### PR DESCRIPTION
**Pull request by vdiravka**
https://drill.apache.org/docs/mongodb-storage-plugin/#configuring-mongodb block has invalid formatting

### CODE REVIEW

**Comment by luocooong** [comment]
Hi, Is it possible to add the mongo docs link about [Connection String URI Format](https://docs.mongodb.com/v3.6/reference/connection-string/)  for this. thanks

**Comment by vdiravka** [comment]
> Hi, Is it possible to add the mongo docs link about [Connection String URI Format](https://docs.mongodb.com/v3.6/reference/connection-string/) for this. thanks

ok, the only thing I will add the reference to `mongo 4.2` page, since Drill has `3.12.7` Mongo Java driver and looks like it supports [Mongo 4.2 version](https://docs.mongodb.com/drivers/java).

**Review by luocooong — APPROVED** [review]
+1

**Comment by vdiravka** [comment]
> > Hi, Is it possible to add the mongo docs link about [Connection String URI Format](https://docs.mongodb.com/v3.6/reference/connection-string/) for this. thanks
> 
> ok, the only thing I will add the reference to `mongo 4.2` page, since Drill has `3.12.7` Mongo Java driver and looks like it supports [Mongo 4.2 version](https://docs.mongodb.com/drivers/java).

Looks like from Docs Drill support 3.0 version officially. Need to check the compatibility with newer Mongo versions before update the doc.

Looks like we should support 3.6 version:
https://issues.apache.org/jira/browse/DRILL-7094

But we need to check and update to latest Mongo version in separate ticket. So added link to 3.0 version for now.

**Pull request merged**
