### PR TITLE
Updated with links to previous releases

### PR DESCRIPTION
**Pull request by kkhatua**
Provides a link for visitors to see current and previous versions of Drill

### CODE REVIEW

**Comment by bbevens** [comment]
Looks good! Thank you!

**Comment by parthchandra** [comment]
For older releases a single link to http://archive.apache.org/dist/drill would be better (you won't have to update this very time there is a release).

**Comment by kkhatua** [comment]
Agreed. We do need a single place for showing the releases. I'll work with Bridget to change at both places.

**Comment by arina-ielchiieva** [comment]
@kkhatua / @parthchandra  should we close the PR or what other work should be done?

**Comment by kkhatua** [comment]
@arina-ielchiieva  I'll change the PR as suggested by Parth. Since Bridget does the merges for _gh-pages_ repo, I'll ask her to close the PR.

**Comment by arina-ielchiieva** [comment]
@kkhatua any update on this?

**Comment by kkhatua** [comment]
Closing this for now. Will reopen as part of a broader set of changes for the website.

**Pull request closed without merging**
