### PR TITLE
DRILL-8409: Support the configuration of bind addresses for network services

### PR DESCRIPTION
**Pull request by jnturton**
# [DRILL-8409](https://issues.apache.org/jira/browse/DRILL-8409): Support the configuration of bind addresses for network services

## Description

Drill provides the DRILL_HOST_NAME env var which determines what Drillbit host name will be exchanged over RPC for later look up by a remote client or Drillbit. This host name is used to check whether Drill is being asked to bind to the loopback address in distributed mode
```
    if (isDistributedMode && InetAddress.getByName(hostName).isLoopbackAddress()) {
      throw new DrillbitStartupException("Drillbit is disallowed to bind to loopback address in distributed mode.");
    }
```
but is not ever used set the bind address used for the Drillbit's RPC and web ports! This PR adds new boot options
```
drill.exec.rpc.bind_addr
drill.exec.http.bind_addr
```
and uses them to set the bind addresses used for RPC services and the HTTP service respectively.

## Documentation
Document all three of DRILL_HOST_NAME and the two new bind address options.

## Testing
Provide no bind addresses and confirm that the effective previous default (0.0.0.0) is applied.
Manually set bind addresses and test that Drill is not accessible on other local addresses.

### CODE REVIEW

**Comment by jnturton** [comment]
I've added two unrelated minor changes implementing safe calls to close() methods. Currently when these calls fail due to some earlier error they drown interesting messages out in unhelpful NPE noise.

**Comment by jnturton** [comment]
> LGTM +1. Do we need any doc updates for this?

Yes I need to document the two new boot options, thanks.

**Comment by rymarm** [comment]
@jnturton Sorry for the late review. The only thing that I would add is a mention of `drill.exec.rpc.bind_addr` and `drill.exec.http.bind_addr` in [`drill-override-example.conf`](https://github.com/apache/drill/blob/master/distribution/src/main/resources/drill-override-example.conf) if this file is still maintainable of course. In addition to our documentation.

**Comment by jnturton** [comment]
> LGTM +1. Do we need any doc updates for this?

Documented.

**Comment by jnturton** [comment]
> @jnturton Sorry for the late review. The only thing that I would add is a mention of `drill.exec.rpc.bind_addr` and `drill.exec.http.bind_addr` in [`drill-override-example.conf`](https://github.com/apache/drill/blob/master/distribution/src/main/resources/drill-override-example.conf) if this file is still maintainable of course. In addition to our documentation.

See #2782 .

**Pull request merged**
